<?php

/**
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Ip_messaging
 * This is the public Twilio REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Twilio\Rest\IpMessaging\V1\Service\Channel;

use Twilio\Options;
use Twilio\Values;

abstract class MessageOptions
{
	/**
	 * @return CreateMessageOptions Options builder
	 */
	public static function create(
		string $from = Values::NONE,
		string $attributes = Values::NONE
	) : CreateMessageOptions
	{
		return new CreateMessageOptions(
			$from,
			$attributes
		);
	}

	/**
	 * @return ReadMessageOptions Options builder
	 */
	public static function read(
		string $order = Values::NONE
	) : ReadMessageOptions
	{
		return new ReadMessageOptions(
			$order
		);
	}

	/**
	 * @return UpdateMessageOptions Options builder
	 */
	public static function update(
		string $body = Values::NONE,
		string $attributes = Values::NONE
	) : UpdateMessageOptions
	{
		return new UpdateMessageOptions(
			$body,
			$attributes
		);
	}
}

class CreateMessageOptions extends Options
	{
	public function __construct(
		string $from = Values::NONE,
		string $attributes = Values::NONE
	) {
		$this->options['from'] = $from;
		$this->options['attributes'] = $attributes;
	}

	/**
	 * Provide a friendly representation
	 *
	 * @return string Machine friendly representation
	 */
	public function __toString() : string
	{
		$options = \http_build_query(Values::of($this->options), '', ' ');

		return '[Twilio.IpMessaging.V1.CreateMessageOptions ' . $options . ']';
	}

	/**
	 *
	 *
	 * @return $this Fluent Builder
	 */
	public function setAttributes(string $attributes) : self
	{
		$this->options['attributes'] = $attributes;

		return $this;
	}

	/**
	 *
	 *
	 * @return $this Fluent Builder
	 */
	public function setFrom(string $from) : self
	{
		$this->options['from'] = $from;

		return $this;
	}
}



class ReadMessageOptions extends Options
	{
	public function __construct(
		string $order = Values::NONE
	) {
		$this->options['order'] = $order;
	}

	/**
	 * Provide a friendly representation
	 *
	 * @return string Machine friendly representation
	 */
	public function __toString() : string
	{
		$options = \http_build_query(Values::of($this->options), '', ' ');

		return '[Twilio.IpMessaging.V1.ReadMessageOptions ' . $options . ']';
	}

	/**
	 *
	 *
	 * @return $this Fluent Builder
	 */
	public function setOrder(string $order) : self
	{
		$this->options['order'] = $order;

		return $this;
	}
}

class UpdateMessageOptions extends Options
	{
	public function __construct(
		string $body = Values::NONE,
		string $attributes = Values::NONE
	) {
		$this->options['body'] = $body;
		$this->options['attributes'] = $attributes;
	}

	/**
	 * Provide a friendly representation
	 *
	 * @return string Machine friendly representation
	 */
	public function __toString() : string
	{
		$options = \http_build_query(Values::of($this->options), '', ' ');

		return '[Twilio.IpMessaging.V1.UpdateMessageOptions ' . $options . ']';
	}

	/**
	 *
	 *
	 * @return $this Fluent Builder
	 */
	public function setAttributes(string $attributes) : self
	{
		$this->options['attributes'] = $attributes;

		return $this;
	}

	/**
	 *
	 *
	 * @return $this Fluent Builder
	 */
	public function setBody(string $body) : self
	{
		$this->options['body'] = $body;

		return $this;
	}
}
