<?php

namespace App\Record\Validation;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateValidators.php table_name
 */
class AdditionalEmail extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, array<string>> */
	public static array $validators = [
		'email' => ['required', 'maxlength'],
		'memberId' => ['required', 'integer'],
		'verified' => ['required', 'integer'],
	];

	public function __construct(\App\Record\AdditionalEmail $record)
		{
		parent::__construct($record);
		}
	}
