<?php

namespace App\Record\Validation;

/**
 * Autogenerated. File will not be changed by oneOffScripts\generateValidators.php.  Delete and rerun if you want.
 */
class AssistantLeaderType extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'assistantLeaderTypeId' => ['required', 'integer'],
		'name' => ['required', 'maxlength'],
		'volunteerPoints' => ['required', 'integer'],
	];
	}
