<?php

namespace App\Record\Validation;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateValidators.php table_name
 */
class Banner extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, array<string>> */
	public static array $validators = [
		'css' => ['maxlength'],
		'description' => ['maxlength'],
		'endDate' => ['required', 'date', 'gte_field:startDate'],
		'fileNameExt' => ['maxlength'],
		'html' => ['maxlength'],
		'js' => ['maxlength'],
		'pending' => ['required', 'integer'],
		'startDate' => ['required', 'date', 'lte_field:endDate'],
		'url' => ['maxlength', 'website'],
	];

	public function __construct(\App\Record\Banner $record)
		{
		parent::__construct($record);
		}
	}
