<?php

namespace App\Record\Validation;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateValidators.php table_name
 */
class BikeShop extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, array<string>> */
	public static array $validators = [
		'address' => ['maxlength'],
		'bikeShopAreaId' => ['integer'],
		'contact' => ['maxlength'],
		'email' => ['maxlength'],
		'name' => ['maxlength'],
		'notes' => ['maxlength'],
		'phone' => ['maxlength'],
		'state' => ['maxlength'],
		'town' => ['maxlength'],
		'url' => ['maxlength'],
		'zip' => ['maxlength'],
	];

	public function __construct(\App\Record\BikeShop $record)
		{
		parent::__construct($record);
		}
	}
