<?php

namespace App\Record\Validation;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateValidators.php table_name
 */
class Calendar extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, array<string>> */
	public static array $validators = [
		'description' => ['maxlength'],
		'distances' => ['maxlength'],
		'eventDate' => ['required', 'date'],
		'eventDays' => ['integer'],
		'eventType' => ['integer'],
		'location' => ['maxlength'],
		'pending' => ['required', 'integer'],
		'price' => ['integer'],
		'privateContact' => ['maxlength'],
		'privateEmail' => ['maxlength'],
		'publicContact' => ['maxlength'],
		'publicEmail' => ['maxlength'],
		'startTime' => ['time'],
		'state' => ['maxlength'],
		'title' => ['maxlength'],
		'webSite' => ['maxlength'],
	];

	public function __construct(\App\Record\Calendar $record)
		{
		parent::__construct($record);
		}
	}
