<?php

namespace App\Record\Validation;

/**
 * Autogenerated. File will not be changed by oneOffScripts\generateValidators.php.  Delete and rerun if you want.
 */
class Category extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'category' => ['maxlength'],
		'coordinatorId' => ['required', 'integer'],
		'categoryId' => ['required', 'integer'],
		'description' => ['maxlength'],
		'maxSpeed' => ['maxlength'],
		'memberDefault' => ['required', 'integer'],
		'minSpeed' => ['maxlength'],
		'ordering' => ['required', 'integer'],
	];
	}
