<?php

namespace App\Record\Validation;

/**
 * Autogenerated. File will not be changed by oneOffScripts\generateValidators.php.  Delete and rerun if you want.
 */
class CueSheet extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'RWGPSId' => ['integer'],
		'cueSheetId' => ['integer'],
		'dateAdded' => ['required', 'maxlength', 'date'],
		'description' => ['maxlength'],
		'destination' => ['maxlength'],
		'elevation' => ['integer'],
		'memberId' => ['integer'],
		'mileage' => ['number'],
		'name' => ['maxlength'],
		'pending' => ['required', 'integer'],
		'pointsAwarded' => ['required', 'integer'],
		'revisionDate' => ['maxlength', 'date'],
		'startLocationId' => ['integer'],
		'terrainId' => ['integer'],
	];
	}
