<?php

namespace App\Record\Validation;

/**
 * Autogenerated. File will not be changed by oneOffScripts\generateValidators.php.  Delete and rerun if you want.
 */
class DiscountCode extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'cashOnly' => ['required', 'integer'],
		'description' => ['maxlength'],
		'discount' => ['required', 'number'],
		'discountCode' => ['maxlength'],
		'discountCodeId' => ['integer'],
		'expirationDate' => ['required', 'maxlength', 'date'],
		'maximumUses' => ['integer'],
		'repeatCount' => ['integer'],
		'startDate' => ['required', 'maxlength', 'date'],
		'type' => ['required', 'integer'],
		'validItemNumbers' => ['maxlength'],
	];
	}
