<?php

namespace App\Record\Validation;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateValidators.php table_name
 */
class DiscountCode extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, array<string>> */
	public static array $validators = [
		'description' => ['maxlength'],
		'discount' => ['number'],
		'discountCode' => ['maxlength'],
		'expirationDate' => ['required', 'date'],
		'maximumUses' => ['integer'],
		'repeatCount' => ['integer'],
		'startDate' => ['required', 'date'],
		'validItemNumbers' => ['maxlength'],
	];

	public function __construct(\App\Record\DiscountCode $record)
		{
		parent::__construct($record);
		}
	}
