<?php

namespace App\Record\Validation;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateValidators.php table_name
 */
class FileFolder extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, array<string>> */
	public static array $validators = [
		'fileFolder' => ['required', 'maxlength'],
		'parentId' => ['integer'],
	];

	public function __construct(\App\Record\FileFolder $record)
		{
		parent::__construct($record);
		}
	}
