<?php

namespace App\Record\Validation;

/**
 * Autogenerated. File will not be changed by oneOffScripts\generateValidators.php.  Delete and rerun if you want.
 */
class ForumMessage extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'forumId' => ['integer'],
		'forumMessageId' => ['integer'],
		'htmlMessage' => ['maxlength'],
		'lastEdited' => ['maxlength', 'datetime'],
		'lastEditorId' => ['integer'],
		'memberId' => ['required', 'integer'],
		'posted' => ['required', 'maxlength', 'datetime'],
		'textMessage' => ['maxlength'],
		'title' => ['maxlength'],
	];
	}
