<?php

namespace App\Record\Validation;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateValidators.php table_name
 */
class GaEvent extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, array<string>> */
	public static array $validators = [
		'dayOfRegistration' => ['integer'],
		'description' => ['maxlength'],
		'eventDate' => ['required', 'date', 'gte_field:lastRegistrationDate'],
		'incentiveCount' => ['integer'],
		'incentiveName' => ['maxlength'],
		'includeMembership' => ['integer'],
		'lastRegistrationDate' => ['required', 'date', 'lte_field:eventDate'],
		'live' => ['integer'],
		'location' => ['maxlength', 'required'],
		'maxRegistrants' => ['integer'],
		'otherEvent' => ['integer'],
		'parent' => ['integer'],
		'question' => ['maxlength'],
		'registrar' => ['maxlength'],
		'registrarEmail' => ['maxlength', 'email'],
		'showPreregistration' => ['integer'],
		'signupMessage' => ['maxlength'],
		'title' => ['maxlength', 'required'],
		'volunteerDiscount' => ['integer'],
		'volunteerEvent' => ['integer'],
	];

	public function __construct(\App\Record\GaEvent $record)
		{
		parent::__construct($record);
		}
	}
