<?php

namespace App\Record\Validation;

/**
 * Autogenerated. File will not be changed by oneOffScripts\generateValidators.php.  Delete and rerun if you want.
 */
class GaOption extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'gaEventId' => ['required', 'integer'],
		'gaOptionId' => ['required', 'integer'],
		'maximumAllowed' => ['required', 'integer'],
		'optionName' => ['required', 'maxlength'],
		'ordering' => ['required', 'integer'],
		'csvField' => ['maxlength'],
		'price' => ['number'],
		'required' => ['required', 'integer'],
	];
	}
