<?php

namespace App\Record\Validation;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateValidators.php table_name
 */
class GaRider extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, array<string>> */
	public static array $validators = [
		'address' => ['maxlength'],
		'comments' => ['maxlength'],
		'contact' => ['maxlength'],
		'contactPhone' => ['maxlength'],
		'email' => ['maxlength', 'email'],
		'emailAnnouncements' => ['integer'],
		'firstName' => ['maxlength', 'required'],
		'gaEventId' => ['required', 'integer'],
		'gaIncentiveId' => ['integer'],
		'gaRideId' => ['integer', 'required'],
		'lastName' => ['maxlength', 'required'],
		'memberId' => ['required', 'integer'],
		'pending' => ['required', 'integer'],
		'phone' => ['maxlength'],
		'pricePaid' => ['number'],
		'prize' => ['integer'],
		'referral' => ['integer'],
		'signedUpOn' => ['required', 'datetime'],
		'state' => ['maxlength'],
		'town' => ['maxlength'],
		'zip' => ['maxlength'],
	];

	public function __construct(\App\Record\GaRider $record)
		{
		parent::__construct($record);
		}
	}
