<?php

namespace App\Record\Validation;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateValidators.php table_name
 */
class JobEvent extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, array<string>> */
	public static array $validators = [
		'cutoffDate' => ['date'],
		'date' => ['required', 'date'],
		'email' => ['maxlength'],
		'name' => ['maxlength'],
		'organizer' => ['integer'],
	];

	public function __construct(\App\Record\JobEvent $record)
		{
		parent::__construct($record);
		}
	}
