<?php

namespace App\Record\Validation;

/**
 * Autogenerated. File will not be changed by oneOffScripts\generateValidators.php.  Delete and rerun if you want.
 */
class JobShift extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'endTime' => ['required', 'time'],
		'jobId' => ['integer'],
		'jobShiftId' => ['required', 'integer'],
		'needed' => ['integer'],
		'startTime' => ['required', 'time'],
	];
	}
