<?php

namespace App\Record\Validation;

/**
 * Autogenerated. File will not be changed by oneOffScripts\generateValidators.php.  Delete and rerun if you want.
 */
class Membership extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'address' => ['maxlength', 'required'],
		'affiliation' => ['maxlength'],
		'state' => ['maxlength', 'required'],
		'allowedMembers' => ['required', 'integer'],
		'expires' => ['maxlength', 'date'],
		'joined' => ['maxlength', 'date'],
		'lastRenewed' => ['maxlength', 'date'],
		'membershipId' => ['integer'],
		'pending' => ['required', 'integer'],
		'renews' => ['maxlength', 'date'],
		'subscriptionId' => ['maxlength'],
		'town' => ['maxlength', 'required'],
		'zip' => ['maxlength', 'required'],
	];
	}
