<?php

namespace App\Record\Validation;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateValidators.php table_name
 */
class Newsletter extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, array<string>> */
	public static array $validators = [
		'date' => ['required', 'date'],
		'dateAdded' => ['required', 'date'],
		'html' => ['maxlength'],
		'size' => ['integer'],
	];

	public function __construct(\App\Record\Newsletter $record)
		{
		parent::__construct($record);
		}
	}
