<?php

namespace App\Record\Validation;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateValidators.php table_name
 */
class Redirect extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, array<string>> */
	public static array $validators = [
		'originalUrl' => ['required', 'maxlength'],
		'redirectUrl' => ['required', 'maxlength'],
	];

	public function __construct(\App\Record\Redirect $record)
		{
		parent::__construct($record);
		}
	}
