<?php

namespace App\Record\Validation;

/**
 * Autogenerated. File will not be changed by subsequent runs of oneOffScripts\generateValidators.php.  Delete and rerun if you want.
 */
class RideRWGPS extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'RWGPSId' => ['required', 'integer'],
		'rideId' => ['required', 'integer'],
	];
	}
