<?php

namespace App\Record\Validation;

/**
 * Autogenerated. File will not be changed by oneOffScripts\generateValidators.php.  Delete and rerun if you want.
 */
class RideSignup extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'attended' => ['integer'],
		'comments' => ['maxlength'],
		'memberId' => ['required', 'integer'],
		'rideComments' => ['integer'],
		'rideId' => ['required', 'integer'],
		'signedUpTime' => ['required', 'maxlength', 'datetime'],
		'status' => ['integer'],
	];
	}
