<?php

namespace App\Record\Validation;

/**
 * Autogenerated. File will not be changed by oneOffScripts\generateValidators.php.  Delete and rerun if you want.
 */
class RwgpsComment extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'RWGPSId' => ['required', 'integer'],
		'comment' => ['maxlength'],
		'comments' => ['required', 'maxlength'],
		'lastEdited' => ['required', 'maxlength', 'datetime'],
		'memberId' => ['required', 'integer'],
	];
	}
