<?php

namespace App\Record\Validation;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateValidators.php table_name
 */
class StartLocation extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, array<string>> */
	public static array $validators = [
		'active' => ['integer'],
		'directions' => ['maxlength'],
		'latitude' => ['number'],
		'link' => ['maxlength'],
		'longitude' => ['number'],
		'name' => ['maxlength'],
	];

	public function __construct(\App\Record\StartLocation $record)
		{
		parent::__construct($record);
		}
	}
