<?php

namespace App\Record\Validation;

/**
 * Autogenerated. File will not be changed by oneOffScripts\generateValidators.php.  Delete and rerun if you want.
 */
class StorePhoto extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'extension' => ['maxlength'],
		'filename' => ['maxlength'],
		'sequence' => ['required', 'integer'],
		'storeItemId' => ['required', 'integer'],
		'storePhotoId' => ['integer'],
	];
	}
