<?php

namespace App\Record\Validation;

/**
 * Autogenerated. File will not be changed by oneOffScripts\generateValidators.php.  Delete and rerun if you want.
 */
class StoreItemDetail extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'detailLine' => ['maxlength'],
		'quantity' => ['integer'],
		'storeItemDetailId' => ['required', 'integer'],
		'storeItemId' => ['required', 'integer'],
	];
	}
