<?php

namespace App\Record\Validation;

/**
 * Autogenerated. File will not be changed by subsequent runs of oneOffScripts\generateValidators.php.  Delete and rerun if you want.
 */
class SurveyCrossTab extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'columnName' => ['maxlength'],
		'columnSurveyQuestionId' => ['integer'],
		'description' => ['maxlength'],
		'name' => ['maxlength'],
		'ordering' => ['integer'],
		'percent' => ['integer'],
		'rowName' => ['maxlength'],
		'rowSurveyQuestionId' => ['required', 'integer'],
		'surveyCrossTabId' => ['integer'],
		'surveyId' => ['required', 'integer'],
	];
	}
