version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: vimeo/psalm
    versions:
    - 4.5.0
    - 4.5.1
    - 4.5.2
    - 4.6.2
    - 4.6.3
    - 4.6.4
    - 4.7.0
    - 4.7.1
  - dependency-name: endroid/qr-code
    versions:
    - 4.0.0
    - 4.0.3
    - 4.1.2
  - dependency-name: setasign/fpdf
    versions:
    - 1.8.3
  - dependency-name: friendsofphp/php-cs-fixer
    versions:
    - 2.18.5
    - 2.18.6
  - dependency-name: twilio/sdk
    versions:
    - 6.16.1
    - 6.17.0
    - 6.18.0
    - 6.20.0
    - 6.21.0
  - dependency-name: phpunit/phpunit
    versions:
    - 9.5.4
  - dependency-name: tinymce/tinymce
    versions:
    - 5.7.0
    - 5.7.1
  - dependency-name: alek13/slack
    versions:
    - 2.0.0
    - 2.0.1
  - dependency-name: phpmailer/phpmailer
    versions:
    - 6.3.0
