<?php

/**
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Flex
 * This is the public Twilio REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Twilio\Rest\FlexApi\V1;

use Twilio\Exceptions\TwilioException;
use Twilio\InstanceContext;
use Twilio\Values;
use Twilio\Version;

class ProvisioningStatusContext extends InstanceContext
	{
	/**
	 * Initialize the ProvisioningStatusContext
	 *
	 * @param Version $version Version that contains the resource
	 */
	public function __construct(
		Version $version
	) {
		parent::__construct($version);

		// Path Solution
		$this->solution = [
		];

		$this->uri = '/account/provision/status';
	}

	/**
	 * Provide a friendly representation
	 *
	 * @return string Machine friendly representation
	 */
	public function __toString() : string
	{
		$context = [];

		foreach ($this->solution as $key => $value) {
			$context[] = "{$key}={$value}";
		}

		return '[Twilio.FlexApi.V1.ProvisioningStatusContext ' . \implode(' ', $context) . ']';
	}

	/**
	 * Fetch the ProvisioningStatusInstance
	 *
	 * @throws TwilioException When an HTTP error occurs.
	 * @return ProvisioningStatusInstance Fetched ProvisioningStatusInstance
	 */
	public function fetch() : ProvisioningStatusInstance
	{

		$headers = Values::of(['Content-Type' => 'application/x-www-form-urlencoded']);
		$payload = $this->version->fetch('GET', $this->uri, [], [], $headers);

		return new ProvisioningStatusInstance(
			$this->version,
			$payload
		);
	}
}
