<?php
/*
 * This document has been generated with
 * https://mlocati.github.io/php-cs-fixer-configurator/#version:3.0.0-rc.1|configurator
 * you can change this configuration by importing this file.
 *
 */

$config = include 'vendor/phpfui/phpunit-syntax-coverage/PhpCsFixer.php';
//$config = include 'OneOffScripts/TwilioFixer.php';

return $config->setFinder(PhpCsFixer\Finder::create()
			->exclude('vendor')
			->in(__DIR__.'/App')
			->in(__DIR__.'/oneOffScripts')
			->in(__DIR__.'/www')
			->in(__DIR__.'/Tests')
//			->in(__DIR__.'/Twilio')
			->in(__DIR__.'/NoNameSpace')
//			->in(__DIR__.'/Auth')
//			->in(__DIR__.'/BaconQrCode')
//			->in(__DIR__.'/Brick')
//			->in(__DIR__.'/Carbon')
//			->in(__DIR__.'/Clue')
//			->in(__DIR__.'/DASPRiD')
//			->in(__DIR__.'/DebugBar')
//			->in(__DIR__.'/DeepCopy')
//			->in(__DIR__.'/Dflydev')
//			->in(__DIR__.'/DI')
//			->in(__DIR__.'/Endroid')
//			->in(__DIR__.'/Flow')
//			->in(__DIR__.'/Gitonomy')
//			->in(__DIR__.'/GuzzleHttp')
//			->in(__DIR__.'/Highlight')
//			->in(__DIR__.'/Http')
//			->in(__DIR__.'/ICalendarOrg')
//			->in(__DIR__.'/Ifsnop')
//			->in(__DIR__.'/Illuminate')
//			->in(__DIR__.'/IMAP')
//			->in(__DIR__.'/Intervention')
//			->in(__DIR__.'/Invoker')
//			->in(__DIR__.'/Laminas')
//			->in(__DIR__.'/Laravel')
//			->in(__DIR__.'/League')
//			->in(__DIR__.'/Maknz')
//			->in(__DIR__.'/Mpdf')
//			->in(__DIR__.'/Nette')
//			->in(__DIR__.'/NoNameSpace')
//			->in(__DIR__.'/NumberToWords')
//			->in(__DIR__.'/NXP')
//			->in(__DIR__.'/PayPalCheckoutSdk')
//			->in(__DIR__.'/PayPalHttp')
//			->in(__DIR__.'/phpDocumentor')
//			->in(__DIR__.'/PHPMailer')
//			->in(__DIR__.'/PhpParser')
//			->in(__DIR__.'/Pimple')
//			->in(__DIR__.'/Psr')
//			->in(__DIR__.'/Sample')
//			->in(__DIR__.'/setasign')
//			->in(__DIR__.'/Soundasleep')
//			->in(__DIR__.'/SparkPost')
//			->in(__DIR__.'/Spatie')
//			->in(__DIR__.'/Symfony')
//			->in(__DIR__.'/Tinify')
//			->in(__DIR__.'/Twilio')
//			->in(__DIR__.'/Webklex')
//			->in(__DIR__.'/Webmozart')
//			->in(__DIR__.'/ZBateson')
		  );
