<?php

/**
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Serverless
 * This is the public Twilio REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Twilio\Rest\Serverless\V1;

use Twilio\Deserialize;
use Twilio\Exceptions\TwilioException;
use Twilio\InstanceResource;
use Twilio\Options;
use Twilio\Rest\Serverless\V1\Service\AssetList;
use Twilio\Rest\Serverless\V1\Service\BuildList;
use Twilio\Rest\Serverless\V1\Service\EnvironmentList;
use Twilio\Rest\Serverless\V1\Service\FunctionList;
use Twilio\Values;
use Twilio\Version;

/**
 * @property string|null $sid
 * @property string|null $accountSid
 * @property string|null $friendlyName
 * @property string|null $uniqueName
 * @property bool|null $includeCredentials
 * @property bool|null $uiEditable
 * @property string|null $domainBase
 * @property \DateTime|null $dateCreated
 * @property \DateTime|null $dateUpdated
 * @property string|null $url
 * @property array|null $links
 */
class ServiceInstance extends InstanceResource
{
	protected $_assets;

	protected $_builds;

	protected $_environments;

	protected $_functions;

	/**
	 * Initialize the ServiceInstance
	 *
	 * @param Version $version Version that contains the resource
	 * @param mixed[] $payload The response payload
	 * @param string $sid The `sid` or `unique_name` of the Service resource to delete.
	 */
	public function __construct(Version $version, array $payload, ?string $sid = null)
	{
		parent::__construct($version);

		// Marshaled Properties
		$this->properties = [
			'sid' => Values::array_get($payload, 'sid'),
			'accountSid' => Values::array_get($payload, 'account_sid'),
			'friendlyName' => Values::array_get($payload, 'friendly_name'),
			'uniqueName' => Values::array_get($payload, 'unique_name'),
			'includeCredentials' => Values::array_get($payload, 'include_credentials'),
			'uiEditable' => Values::array_get($payload, 'ui_editable'),
			'domainBase' => Values::array_get($payload, 'domain_base'),
			'dateCreated' => Deserialize::dateTime(Values::array_get($payload, 'date_created')),
			'dateUpdated' => Deserialize::dateTime(Values::array_get($payload, 'date_updated')),
			'url' => Values::array_get($payload, 'url'),
			'links' => Values::array_get($payload, 'links'),
		];

		$this->solution = ['sid' => $sid ?: $this->properties['sid'], ];
	}

	/**
	 * Magic getter to access properties
	 *
	 * @param string $name Property to access
	 * @throws TwilioException For unknown properties
	 * @return mixed The requested property
	 */
	public function __get(string $name)
	{
		if (\array_key_exists($name, $this->properties)) {
			return $this->properties[$name];
		}

		if (\property_exists($this, '_' . $name)) {
			$method = 'get' . \ucfirst($name);

			return $this->{$method}();
		}

		throw new TwilioException('Unknown property: ' . $name);
	}

	/**
	 * Provide a friendly representation
	 *
	 * @return string Machine friendly representation
	 */
	public function __toString() : string
	{
		$context = [];

		foreach ($this->solution as $key => $value) {
			$context[] = "{$key}={$value}";
		}

		return '[Twilio.Serverless.V1.ServiceInstance ' . \implode(' ', $context) . ']';
	}

	/**
	 * Delete the ServiceInstance
	 *
	 * @throws TwilioException When an HTTP error occurs.
	 * @return bool True if delete succeeds, false otherwise
	 */
	public function delete() : bool
	{

		return $this->proxy()->delete();
	}

	/**
	 * Fetch the ServiceInstance
	 *
	 * @throws TwilioException When an HTTP error occurs.
	 * @return ServiceInstance Fetched ServiceInstance
	 */
	public function fetch() : ServiceInstance
	{

		return $this->proxy()->fetch();
	}

	/**
	 * Update the ServiceInstance
	 *
	 * @param array|Options $options Optional Arguments
	 * @throws TwilioException When an HTTP error occurs.
	 * @return ServiceInstance Updated ServiceInstance
	 */
	public function update(array $options = []) : ServiceInstance
	{

		return $this->proxy()->update($options);
	}

	/**
	 * Access the assets
	 */
	protected function getAssets() : AssetList
	{
		return $this->proxy()->assets;
	}

	/**
	 * Access the builds
	 */
	protected function getBuilds() : BuildList
	{
		return $this->proxy()->builds;
	}

	/**
	 * Access the environments
	 */
	protected function getEnvironments() : EnvironmentList
	{
		return $this->proxy()->environments;
	}

	/**
	 * Access the functions
	 */
	protected function getFunctions() : FunctionList
	{
		return $this->proxy()->functions;
	}

	/**
	 * Generate an instance context for the instance, the context is capable of
	 * performing various actions.  All instance actions are proxied to the context
	 *
	 * @return ServiceContext Context for this ServiceInstance
	 */
	protected function proxy() : ServiceContext
	{
		if (! $this->context) {
			$this->context = new ServiceContext(
				$this->version,
				$this->solution['sid']
			);
		}

		return $this->context;
	}
}
