<?php

/**
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Content
 * This is the public Twilio REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Twilio\Rest\Content\V1;

use Twilio\Values;

abstract class ContentModels
{
	/**
	 * @property string $type
	 * @property string $copyCodeText
	 */
	public static function createAuthenticationAction(array $payload = []) : AuthenticationAction
	{
		return new AuthenticationAction($payload);
	}

	/**
	 * @property string $type
	 * @property string $title
	 * @property string $url
	 * @property string $phone
	 * @property string $code
	 */
	public static function createCallToActionAction(array $payload = []) : CallToActionAction
	{
		return new CallToActionAction($payload);
	}

	/**
	 * @property string $type
	 * @property string $title
	 * @property string $url
	 * @property string $phone
	 * @property string $id
	 * @property string $code
	 */
	public static function createCardAction(array $payload = []) : CardAction
	{
		return new CardAction($payload);
	}

	/**
	 * @property string $type
	 * @property string $title
	 * @property string $url
	 * @property string $phone
	 * @property string $id
	 */
	public static function createCarouselAction(array $payload = []) : CarouselAction
	{
		return new CarouselAction($payload);
	}

	/**
	 * @property string $title
	 * @property string $body
	 * @property string $media
	 * @property CarouselAction[] $actions
	 */
	public static function createCarouselCard(array $payload = []) : CarouselCard
	{
		return new CarouselCard($payload);
	}

	/**
	 * @property string $id
	 * @property string $sectionTitle
	 * @property string $name
	 * @property string $mediaUrl
	 * @property string $price
	 * @property string $description
	 */
	public static function createCatalogItem(array $payload = []) : CatalogItem
	{
		return new CatalogItem($payload);
	}

	/**
	 * @property string $friendlyName User defined name of the content
	 * @property array<string,string> $variables Key value pairs of variable name to value
	 * @property string $language Language code for the content
	 * @property Types $types
	 */
	public static function createContentCreateRequest(array $payload = []) : ContentCreateRequest
	{
		return new ContentCreateRequest($payload);
	}

	/**
	 * @property string $id
	 * @property string $nextPageId
	 * @property string $title
	 * @property string $subtitle
	 * @property FlowsPageComponent[] $layout
	 */
	public static function createFlowsPage(array $payload = []) : FlowsPage
	{
		return new FlowsPage($payload);
	}

	/**
	 * @property string $label
	 * @property string $type
	 */
	public static function createFlowsPageComponent(array $payload = []) : FlowsPageComponent
	{
		return new FlowsPageComponent($payload);
	}

	/**
	 * @property string $id
	 * @property string $item
	 * @property string $description
	 */
	public static function createListItem(array $payload = []) : ListItem
	{
		return new ListItem($payload);
	}

	/**
	 * @property string $type
	 * @property string $title
	 * @property string $id
	 */
	public static function createQuickReplyAction(array $payload = []) : QuickReplyAction
	{
		return new QuickReplyAction($payload);
	}

	/**
	 * @property string $body
	 * @property CallToActionAction[] $actions
	 */
	public static function createTwilioCallToAction(array $payload = []) : TwilioCallToAction
	{
		return new TwilioCallToAction($payload);
	}

	/**
	 * @property string $title
	 * @property string $subtitle
	 * @property string[] $media
	 * @property CardAction[] $actions
	 */
	public static function createTwilioCard(array $payload = []) : TwilioCard
	{
		return new TwilioCard($payload);
	}

	/**
	 * @property string $body
	 * @property CarouselCard[] $cards
	 */
	public static function createTwilioCarousel(array $payload = []) : TwilioCarousel
	{
		return new TwilioCarousel($payload);
	}

	/**
	 * @property string $title
	 * @property string $body
	 * @property string $subtitle
	 * @property string $id
	 * @property CatalogItem[] $items
	 * @property string $dynamicItems
	 */
	public static function createTwilioCatalog(array $payload = []) : TwilioCatalog
	{
		return new TwilioCatalog($payload);
	}

	/**
	 * @property string $body
	 * @property string $buttonText
	 * @property string $subtitle
	 * @property string $mediaUrl
	 * @property FlowsPage[] $pages
	 * @property string $type
	 */
	public static function createTwilioFlows(array $payload = []) : TwilioFlows
	{
		return new TwilioFlows($payload);
	}

	/**
	 * @property string $body
	 * @property string $button
	 * @property ListItem[] $items
	 */
	public static function createTwilioListPicker(array $payload = []) : TwilioListPicker
	{
		return new TwilioListPicker($payload);
	}

	/**
	 * @property string $latitude
	 * @property string $longitude
	 * @property string $label
	 */
	public static function createTwilioLocation(array $payload = []) : TwilioLocation
	{
		return new TwilioLocation($payload);
	}

	/**
	 * @property string $body
	 * @property string[] $media
	 */
	public static function createTwilioMedia(array $payload = []) : TwilioMedia
	{
		return new TwilioMedia($payload);
	}

	/**
	 * @property string $body
	 * @property QuickReplyAction[] $actions
	 */
	public static function createTwilioQuickReply(array $payload = []) : TwilioQuickReply
	{
		return new TwilioQuickReply($payload);
	}

	/**
	 * @property string $id
	 * @property string $title
	 * @property string $timeSlots
	 */
	public static function createTwilioSchedule(array $payload = []) : TwilioSchedule
	{
		return new TwilioSchedule($payload);
	}

	/**
	 * @property string $body
	 */
	public static function createTwilioText(array $payload = []) : TwilioText
	{
		return new TwilioText($payload);
	}

	/**
	 * @property TwilioText $twilioText
	 * @property TwilioMedia $twilioMedia
	 * @property TwilioLocation $twilioLocation
	 * @property TwilioListPicker $twilioListPicker
	 * @property TwilioCallToAction $twilioCallToAction
	 * @property TwilioQuickReply $twilioQuickReply
	 * @property TwilioCard $twilioCard
	 * @property TwilioCatalog $twilioCatalog
	 * @property TwilioCarousel $twilioCarousel
	 * @property TwilioFlows $twilioFlows
	 * @property TwilioSchedule $twilioSchedule
	 * @property WhatsappCard $whatsappCard
	 * @property WhatsappAuthentication $whatsappAuthentication
	 */
	public static function createTypes(array $payload = []) : Types
	{
		return new Types($payload);
	}

	/**
	 * @property bool $addSecurityRecommendation
	 * @property string $codeExpirationMinutes
	 * @property AuthenticationAction[] $actions
	 */
	public static function createWhatsappAuthentication(array $payload = []) : WhatsappAuthentication
	{
		return new WhatsappAuthentication($payload);
	}

	/**
	 * @property string $body
	 * @property string $footer
	 * @property string[] $media
	 * @property string $headerText
	 * @property CardAction[] $actions
	 */
	public static function createWhatsappCard(array $payload = []) : WhatsappCard
	{
		return new WhatsappCard($payload);
	}
}

class TwilioText implements \JsonSerializable
{
	/**
	 * @property string $body
	 */
		protected $body;

	public function __construct(array $payload = []) {
		$this->body = Values::array_get($payload, 'body');
	}

	public function jsonSerialize() : array
	{
		return [
			'body' => $this->body
		];
	}

	public function toArray() : array
	{
		return $this->jsonSerialize();
	}
}

class TwilioMedia implements \JsonSerializable
{
	/**
	 * @property string $body
	 * @property string[] $media
	 */
		protected $body;

		protected $media;

	public function __construct(array $payload = []) {
		$this->body = Values::array_get($payload, 'body');
		$this->media = Values::array_get($payload, 'media');
	}

	public function jsonSerialize() : array
	{
		return [
			'body' => $this->body,
			'media' => $this->media
		];
	}

	public function toArray() : array
	{
		return $this->jsonSerialize();
	}
}

class TwilioLocation implements \JsonSerializable
{
		protected $label;

	/**
	 * @property string $latitude
	 * @property string $longitude
	 * @property string $label
	 */
		protected $latitude;

		protected $longitude;

	public function __construct(array $payload = []) {
		$this->latitude = Values::array_get($payload, 'latitude');
		$this->longitude = Values::array_get($payload, 'longitude');
		$this->label = Values::array_get($payload, 'label');
	}

	public function jsonSerialize() : array
	{
		return [
			'latitude' => $this->latitude,
			'longitude' => $this->longitude,
			'label' => $this->label
		];
	}

	public function toArray() : array
	{
		return $this->jsonSerialize();
	}
}

class ListItem implements \JsonSerializable
{
		protected $description;

	/**
	 * @property string $id
	 * @property string $item
	 * @property string $description
	 */
		protected $id;

		protected $item;

	public function __construct(array $payload = []) {
		$this->id = Values::array_get($payload, 'id');
		$this->item = Values::array_get($payload, 'item');
		$this->description = Values::array_get($payload, 'description');
	}

	public function jsonSerialize() : array
	{
		return [
			'id' => $this->id,
			'item' => $this->item,
			'description' => $this->description
		];
	}

	public function toArray() : array
	{
		return $this->jsonSerialize();
	}
}

class TwilioListPicker implements \JsonSerializable
{
	/**
	 * @property string $body
	 * @property string $button
	 * @property ListItem[] $items
	 */
		protected $body;

		protected $button;

		protected $items;

	public function __construct(array $payload = []) {
		$this->body = Values::array_get($payload, 'body');
		$this->button = Values::array_get($payload, 'button');
		$this->items = Values::array_get($payload, 'items');
	}

	public function jsonSerialize() : array
	{
		return [
			'body' => $this->body,
			'button' => $this->button,
			'items' => $this->items
		];
	}

	public function toArray() : array
	{
		return $this->jsonSerialize();
	}
}

class CallToActionAction implements \JsonSerializable
{
		protected $code;

		protected $phone;

		protected $title;

	/**
	 * @property string $type
	 * @property string $title
	 * @property string $url
	 * @property string $phone
	 * @property string $code
	 */
		protected $type;

		protected $url;

	public function __construct(array $payload = []) {
		$this->type = Values::array_get($payload, 'type');
		$this->title = Values::array_get($payload, 'title');
		$this->url = Values::array_get($payload, 'url');
		$this->phone = Values::array_get($payload, 'phone');
		$this->code = Values::array_get($payload, 'code');
	}

	public function jsonSerialize() : array
	{
		return [
			'type' => $this->type,
			'title' => $this->title,
			'url' => $this->url,
			'phone' => $this->phone,
			'code' => $this->code
		];
	}

	public function toArray() : array
	{
		return $this->jsonSerialize();
	}
}

class TwilioCallToAction implements \JsonSerializable
{
		protected $actions;

	/**
	 * @property string $body
	 * @property CallToActionAction[] $actions
	 */
		protected $body;

	public function __construct(array $payload = []) {
		$this->body = Values::array_get($payload, 'body');
		$this->actions = Values::array_get($payload, 'actions');
	}

	public function jsonSerialize() : array
	{
		return [
			'body' => $this->body,
			'actions' => $this->actions
		];
	}

	public function toArray() : array
	{
		return $this->jsonSerialize();
	}
}

class QuickReplyAction implements \JsonSerializable
{
		protected $id;

		protected $title;

	/**
	 * @property string $type
	 * @property string $title
	 * @property string $id
	 */
		protected $type;

	public function __construct(array $payload = []) {
		$this->type = Values::array_get($payload, 'type');
		$this->title = Values::array_get($payload, 'title');
		$this->id = Values::array_get($payload, 'id');
	}

	public function jsonSerialize() : array
	{
		return [
			'type' => $this->type,
			'title' => $this->title,
			'id' => $this->id
		];
	}

	public function toArray() : array
	{
		return $this->jsonSerialize();
	}
}

class TwilioQuickReply implements \JsonSerializable
{
		protected $actions;

	/**
	 * @property string $body
	 * @property QuickReplyAction[] $actions
	 */
		protected $body;

	public function __construct(array $payload = []) {
		$this->body = Values::array_get($payload, 'body');
		$this->actions = Values::array_get($payload, 'actions');
	}

	public function jsonSerialize() : array
	{
		return [
			'body' => $this->body,
			'actions' => $this->actions
		];
	}

	public function toArray() : array
	{
		return $this->jsonSerialize();
	}
}

class CardAction implements \JsonSerializable
{
		protected $code;

		protected $id;

		protected $phone;

		protected $title;

	/**
	 * @property string $type
	 * @property string $title
	 * @property string $url
	 * @property string $phone
	 * @property string $id
	 * @property string $code
	 */
		protected $type;

		protected $url;

	public function __construct(array $payload = []) {
		$this->type = Values::array_get($payload, 'type');
		$this->title = Values::array_get($payload, 'title');
		$this->url = Values::array_get($payload, 'url');
		$this->phone = Values::array_get($payload, 'phone');
		$this->id = Values::array_get($payload, 'id');
		$this->code = Values::array_get($payload, 'code');
	}

	public function jsonSerialize() : array
	{
		return [
			'type' => $this->type,
			'title' => $this->title,
			'url' => $this->url,
			'phone' => $this->phone,
			'id' => $this->id,
			'code' => $this->code
		];
	}

	public function toArray() : array
	{
		return $this->jsonSerialize();
	}
}

class TwilioCard implements \JsonSerializable
{
		protected $actions;

		protected $media;

		protected $subtitle;

	/**
	 * @property string $title
	 * @property string $subtitle
	 * @property string[] $media
	 * @property CardAction[] $actions
	 */
		protected $title;

	public function __construct(array $payload = []) {
		$this->title = Values::array_get($payload, 'title');
		$this->subtitle = Values::array_get($payload, 'subtitle');
		$this->media = Values::array_get($payload, 'media');
		$this->actions = Values::array_get($payload, 'actions');
	}

	public function jsonSerialize() : array
	{
		return [
			'title' => $this->title,
			'subtitle' => $this->subtitle,
			'media' => $this->media,
			'actions' => $this->actions
		];
	}

	public function toArray() : array
	{
		return $this->jsonSerialize();
	}
}

class CatalogItem implements \JsonSerializable
{
		protected $description;

	/**
	 * @property string $id
	 * @property string $sectionTitle
	 * @property string $name
	 * @property string $mediaUrl
	 * @property string $price
	 * @property string $description
	 */
		protected $id;

		protected $mediaUrl;

		protected $name;

		protected $price;

		protected $sectionTitle;

	public function __construct(array $payload = []) {
		$this->id = Values::array_get($payload, 'id');
		$this->sectionTitle = Values::array_get($payload, 'section_title');
		$this->name = Values::array_get($payload, 'name');
		$this->mediaUrl = Values::array_get($payload, 'media_url');
		$this->price = Values::array_get($payload, 'price');
		$this->description = Values::array_get($payload, 'description');
	}

	public function jsonSerialize() : array
	{
		return [
			'id' => $this->id,
			'section_title' => $this->sectionTitle,
			'name' => $this->name,
			'media_url' => $this->mediaUrl,
			'price' => $this->price,
			'description' => $this->description
		];
	}

	public function toArray() : array
	{
		return $this->jsonSerialize();
	}
}

class TwilioCatalog implements \JsonSerializable
{
		protected $body;

		protected $dynamicItems;

		protected $id;

		protected $items;

		protected $subtitle;

	/**
	 * @property string $title
	 * @property string $body
	 * @property string $subtitle
	 * @property string $id
	 * @property CatalogItem[] $items
	 * @property string $dynamicItems
	 */
		protected $title;

	public function __construct(array $payload = []) {
		$this->title = Values::array_get($payload, 'title');
		$this->body = Values::array_get($payload, 'body');
		$this->subtitle = Values::array_get($payload, 'subtitle');
		$this->id = Values::array_get($payload, 'id');
		$this->items = Values::array_get($payload, 'items');
		$this->dynamicItems = Values::array_get($payload, 'dynamic_items');
	}

	public function jsonSerialize() : array
	{
		return [
			'title' => $this->title,
			'body' => $this->body,
			'subtitle' => $this->subtitle,
			'id' => $this->id,
			'items' => $this->items,
			'dynamic_items' => $this->dynamicItems
		];
	}

	public function toArray() : array
	{
		return $this->jsonSerialize();
	}
}

class CarouselAction implements \JsonSerializable
{
		protected $id;

		protected $phone;

		protected $title;

	/**
	 * @property string $type
	 * @property string $title
	 * @property string $url
	 * @property string $phone
	 * @property string $id
	 */
		protected $type;

		protected $url;

	public function __construct(array $payload = []) {
		$this->type = Values::array_get($payload, 'type');
		$this->title = Values::array_get($payload, 'title');
		$this->url = Values::array_get($payload, 'url');
		$this->phone = Values::array_get($payload, 'phone');
		$this->id = Values::array_get($payload, 'id');
	}

	public function jsonSerialize() : array
	{
		return [
			'type' => $this->type,
			'title' => $this->title,
			'url' => $this->url,
			'phone' => $this->phone,
			'id' => $this->id
		];
	}

	public function toArray() : array
	{
		return $this->jsonSerialize();
	}
}

class CarouselCard implements \JsonSerializable
{
		protected $actions;

		protected $body;

		protected $media;

	/**
	 * @property string $title
	 * @property string $body
	 * @property string $media
	 * @property CarouselAction[] $actions
	 */
		protected $title;

	public function __construct(array $payload = []) {
		$this->title = Values::array_get($payload, 'title');
		$this->body = Values::array_get($payload, 'body');
		$this->media = Values::array_get($payload, 'media');
		$this->actions = Values::array_get($payload, 'actions');
	}

	public function jsonSerialize() : array
	{
		return [
			'title' => $this->title,
			'body' => $this->body,
			'media' => $this->media,
			'actions' => $this->actions
		];
	}

	public function toArray() : array
	{
		return $this->jsonSerialize();
	}
}

class TwilioCarousel implements \JsonSerializable
{
	/**
	 * @property string $body
	 * @property CarouselCard[] $cards
	 */
		protected $body;

		protected $cards;

	public function __construct(array $payload = []) {
		$this->body = Values::array_get($payload, 'body');
		$this->cards = Values::array_get($payload, 'cards');
	}

	public function jsonSerialize() : array
	{
		return [
			'body' => $this->body,
			'cards' => $this->cards
		];
	}

	public function toArray() : array
	{
		return $this->jsonSerialize();
	}
}

class FlowsPageComponent implements \JsonSerializable
{
	/**
	 * @property string $label
	 * @property string $type
	 */
		protected $label;

		protected $type;

	public function __construct(array $payload = []) {
		$this->label = Values::array_get($payload, 'label');
		$this->type = Values::array_get($payload, 'type');
	}

	public function jsonSerialize() : array
	{
		return [
			'label' => $this->label,
			'type' => $this->type
		];
	}

	public function toArray() : array
	{
		return $this->jsonSerialize();
	}
}

class FlowsPage implements \JsonSerializable
{
	/**
	 * @property string $id
	 * @property string $nextPageId
	 * @property string $title
	 * @property string $subtitle
	 * @property FlowsPageComponent[] $layout
	 */
		protected $id;

		protected $layout;

		protected $nextPageId;

		protected $subtitle;

		protected $title;

	public function __construct(array $payload = []) {
		$this->id = Values::array_get($payload, 'id');
		$this->nextPageId = Values::array_get($payload, 'next_page_id');
		$this->title = Values::array_get($payload, 'title');
		$this->subtitle = Values::array_get($payload, 'subtitle');
		$this->layout = Values::array_get($payload, 'layout');
	}

	public function jsonSerialize() : array
	{
		return [
			'id' => $this->id,
			'next_page_id' => $this->nextPageId,
			'title' => $this->title,
			'subtitle' => $this->subtitle,
			'layout' => $this->layout
		];
	}

	public function toArray() : array
	{
		return $this->jsonSerialize();
	}
}

class TwilioFlows implements \JsonSerializable
{
	/**
	 * @property string $body
	 * @property string $buttonText
	 * @property string $subtitle
	 * @property string $mediaUrl
	 * @property FlowsPage[] $pages
	 * @property string $type
	 */
		protected $body;

		protected $buttonText;

		protected $mediaUrl;

		protected $pages;

		protected $subtitle;

		protected $type;

	public function __construct(array $payload = []) {
		$this->body = Values::array_get($payload, 'body');
		$this->buttonText = Values::array_get($payload, 'button_text');
		$this->subtitle = Values::array_get($payload, 'subtitle');
		$this->mediaUrl = Values::array_get($payload, 'media_url');
		$this->pages = Values::array_get($payload, 'pages');
		$this->type = Values::array_get($payload, 'type');
	}

	public function jsonSerialize() : array
	{
		return [
			'body' => $this->body,
			'button_text' => $this->buttonText,
			'subtitle' => $this->subtitle,
			'media_url' => $this->mediaUrl,
			'pages' => $this->pages,
			'type' => $this->type
		];
	}

	public function toArray() : array
	{
		return $this->jsonSerialize();
	}
}

class TwilioSchedule implements \JsonSerializable
{
	/**
	 * @property string $id
	 * @property string $title
	 * @property string $timeSlots
	 */
		protected $id;

		protected $timeSlots;

		protected $title;

	public function __construct(array $payload = []) {
		$this->id = Values::array_get($payload, 'id');
		$this->title = Values::array_get($payload, 'title');
		$this->timeSlots = Values::array_get($payload, 'timeSlots');
	}

	public function jsonSerialize() : array
	{
		return [
			'id' => $this->id,
			'title' => $this->title,
			'timeSlots' => $this->timeSlots
		];
	}

	public function toArray() : array
	{
		return $this->jsonSerialize();
	}
}

class WhatsappCard implements \JsonSerializable
{
		protected $actions;

	/**
	 * @property string $body
	 * @property string $footer
	 * @property string[] $media
	 * @property string $headerText
	 * @property CardAction[] $actions
	 */
		protected $body;

		protected $footer;

		protected $headerText;

		protected $media;

	public function __construct(array $payload = []) {
		$this->body = Values::array_get($payload, 'body');
		$this->footer = Values::array_get($payload, 'footer');
		$this->media = Values::array_get($payload, 'media');
		$this->headerText = Values::array_get($payload, 'header_text');
		$this->actions = Values::array_get($payload, 'actions');
	}

	public function jsonSerialize() : array
	{
		return [
			'body' => $this->body,
			'footer' => $this->footer,
			'media' => $this->media,
			'header_text' => $this->headerText,
			'actions' => $this->actions
		];
	}

	public function toArray() : array
	{
		return $this->jsonSerialize();
	}
}

class AuthenticationAction implements \JsonSerializable
{
		protected $copyCodeText;

	/**
	 * @property string $type
	 * @property string $copyCodeText
	 */
		protected $type;

	public function __construct(array $payload = []) {
		$this->type = Values::array_get($payload, 'type');
		$this->copyCodeText = Values::array_get($payload, 'copy_code_text');
	}

	public function jsonSerialize() : array
	{
		return [
			'type' => $this->type,
			'copy_code_text' => $this->copyCodeText
		];
	}

	public function toArray() : array
	{
		return $this->jsonSerialize();
	}
}

class WhatsappAuthentication implements \JsonSerializable
{
		protected $actions;

	/**
	 * @property bool $addSecurityRecommendation
	 * @property string $codeExpirationMinutes
	 * @property AuthenticationAction[] $actions
	 */
		protected $addSecurityRecommendation;

		protected $codeExpirationMinutes;

	public function __construct(array $payload = []) {
		$this->addSecurityRecommendation = Values::array_get($payload, 'add_security_recommendation');
		$this->codeExpirationMinutes = Values::array_get($payload, 'code_expiration_minutes');
		$this->actions = Values::array_get($payload, 'actions');
	}

	public function jsonSerialize() : array
	{
		return [
			'add_security_recommendation' => $this->addSecurityRecommendation,
			'code_expiration_minutes' => $this->codeExpirationMinutes,
			'actions' => $this->actions
		];
	}

	public function toArray() : array
	{
		return $this->jsonSerialize();
	}
}

class Types implements \JsonSerializable
{
		protected $twilioCallToAction;

		protected $twilioCard;

		protected $twilioCarousel;

		protected $twilioCatalog;

		protected $twilioFlows;

		protected $twilioListPicker;

		protected $twilioLocation;

		protected $twilioMedia;

		protected $twilioQuickReply;

		protected $twilioSchedule;

	/**
	 * @property TwilioText $twilioText
	 * @property TwilioMedia $twilioMedia
	 * @property TwilioLocation $twilioLocation
	 * @property TwilioListPicker $twilioListPicker
	 * @property TwilioCallToAction $twilioCallToAction
	 * @property TwilioQuickReply $twilioQuickReply
	 * @property TwilioCard $twilioCard
	 * @property TwilioCatalog $twilioCatalog
	 * @property TwilioCarousel $twilioCarousel
	 * @property TwilioFlows $twilioFlows
	 * @property TwilioSchedule $twilioSchedule
	 * @property WhatsappCard $whatsappCard
	 * @property WhatsappAuthentication $whatsappAuthentication
	 */
		protected $twilioText;

		protected $whatsappAuthentication;

		protected $whatsappCard;

	public function __construct(array $payload = []) {
		$this->twilioText = Values::array_get($payload, 'twilio/text');
		$this->twilioMedia = Values::array_get($payload, 'twilio/media');
		$this->twilioLocation = Values::array_get($payload, 'twilio/location');
		$this->twilioListPicker = Values::array_get($payload, 'twilio/list-picker');
		$this->twilioCallToAction = Values::array_get($payload, 'twilio/call-to-action');
		$this->twilioQuickReply = Values::array_get($payload, 'twilio/quick-reply');
		$this->twilioCard = Values::array_get($payload, 'twilio/card');
		$this->twilioCatalog = Values::array_get($payload, 'twilio/catalog');
		$this->twilioCarousel = Values::array_get($payload, 'twilio/carousel');
		$this->twilioFlows = Values::array_get($payload, 'twilio/flows');
		$this->twilioSchedule = Values::array_get($payload, 'twilio/schedule');
		$this->whatsappCard = Values::array_get($payload, 'whatsapp/card');
		$this->whatsappAuthentication = Values::array_get($payload, 'whatsapp/authentication');
	}

	public function jsonSerialize() : array
	{
		return [
			'twilio/text' => $this->twilioText,
			'twilio/media' => $this->twilioMedia,
			'twilio/location' => $this->twilioLocation,
			'twilio/list-picker' => $this->twilioListPicker,
			'twilio/call-to-action' => $this->twilioCallToAction,
			'twilio/quick-reply' => $this->twilioQuickReply,
			'twilio/card' => $this->twilioCard,
			'twilio/catalog' => $this->twilioCatalog,
			'twilio/carousel' => $this->twilioCarousel,
			'twilio/flows' => $this->twilioFlows,
			'twilio/schedule' => $this->twilioSchedule,
			'whatsapp/card' => $this->whatsappCard,
			'whatsapp/authentication' => $this->whatsappAuthentication
		];
	}

	public function toArray() : array
	{
		return $this->jsonSerialize();
	}
}

class ContentCreateRequest implements \JsonSerializable
{
	/**
	 * @property string $friendlyName User defined name of the content
	 * @property array<string,string> $variables Key value pairs of variable name to value
	 * @property string $language Language code for the content
	 * @property Types $types
	 */
		protected $friendlyName;

		protected $language;

		protected $types;

		protected $variables;

	public function __construct(array $payload = []) {
		$this->friendlyName = Values::array_get($payload, 'friendly_name');
		$this->variables = Values::array_get($payload, 'variables');
		$this->language = Values::array_get($payload, 'language');
		$this->types = Values::array_get($payload, 'types');
	}

	public function jsonSerialize() : array
	{
		return [
			'friendly_name' => $this->friendlyName,
			'variables' => $this->variables,
			'language' => $this->language,
			'types' => $this->types
		];
	}

	public function toArray() : array
	{
		return $this->jsonSerialize();
	}
}
