<?php

/**
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Chat
 * This is the public Twilio REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Twilio\Rest\Chat\V2\Service\User;

use Twilio\Options;
use Twilio\Values;

abstract class UserChannelOptions
{
	/**
	 * @param string $xTwilioWebhookEnabled The X-Twilio-Webhook-Enabled HTTP request header
	 * @return DeleteUserChannelOptions Options builder
	 */
	public static function delete(
		string $xTwilioWebhookEnabled = Values::NONE
	) : DeleteUserChannelOptions
	{
		return new DeleteUserChannelOptions(
			$xTwilioWebhookEnabled
		);
	}

	/**
	 * @param int $lastConsumedMessageIndex The index of the last [Message](https://www.twilio.com/docs/chat/rest/message-resource) in the [Channel](https://www.twilio.com/docs/chat/channels) that the Member has read.
	 * @param \DateTime $lastConsumptionTimestamp The [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) timestamp of the last [Message](https://www.twilio.com/docs/chat/rest/message-resource) read event for the Member within the [Channel](https://www.twilio.com/docs/chat/channels).
	 * @return UpdateUserChannelOptions Options builder
	 */
	public static function update(
		string $notificationLevel = Values::NONE,
		int $lastConsumedMessageIndex = Values::INT_NONE,
		?\DateTime $lastConsumptionTimestamp = null
	) : UpdateUserChannelOptions
	{
		return new UpdateUserChannelOptions(
			$notificationLevel,
			$lastConsumedMessageIndex,
			$lastConsumptionTimestamp
		);
	}
}

class DeleteUserChannelOptions extends Options
	{
	/**
	 * @param string $xTwilioWebhookEnabled The X-Twilio-Webhook-Enabled HTTP request header
	 */
	public function __construct(
		string $xTwilioWebhookEnabled = Values::NONE
	) {
		$this->options['xTwilioWebhookEnabled'] = $xTwilioWebhookEnabled;
	}

	/**
	 * Provide a friendly representation
	 *
	 * @return string Machine friendly representation
	 */
	public function __toString() : string
	{
		$options = \http_build_query(Values::of($this->options), '', ' ');

		return '[Twilio.Chat.V2.DeleteUserChannelOptions ' . $options . ']';
	}

	/**
	 * The X-Twilio-Webhook-Enabled HTTP request header
	 *
	 * @param string $xTwilioWebhookEnabled The X-Twilio-Webhook-Enabled HTTP request header
	 * @return $this Fluent Builder
	 */
	public function setXTwilioWebhookEnabled(string $xTwilioWebhookEnabled) : self
	{
		$this->options['xTwilioWebhookEnabled'] = $xTwilioWebhookEnabled;

		return $this;
	}
}



class UpdateUserChannelOptions extends Options
	{
	/**
	 * @param int $lastConsumedMessageIndex The index of the last [Message](https://www.twilio.com/docs/chat/rest/message-resource) in the [Channel](https://www.twilio.com/docs/chat/channels) that the Member has read.
	 * @param \DateTime $lastConsumptionTimestamp The [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) timestamp of the last [Message](https://www.twilio.com/docs/chat/rest/message-resource) read event for the Member within the [Channel](https://www.twilio.com/docs/chat/channels).
	 */
	public function __construct(
		string $notificationLevel = Values::NONE,
		int $lastConsumedMessageIndex = Values::INT_NONE,
		?\DateTime $lastConsumptionTimestamp = null
	) {
		$this->options['notificationLevel'] = $notificationLevel;
		$this->options['lastConsumedMessageIndex'] = $lastConsumedMessageIndex;
		$this->options['lastConsumptionTimestamp'] = $lastConsumptionTimestamp;
	}

	/**
	 * Provide a friendly representation
	 *
	 * @return string Machine friendly representation
	 */
	public function __toString() : string
	{
		$options = \http_build_query(Values::of($this->options), '', ' ');

		return '[Twilio.Chat.V2.UpdateUserChannelOptions ' . $options . ']';
	}

	/**
	 * The index of the last [Message](https://www.twilio.com/docs/chat/rest/message-resource) in the [Channel](https://www.twilio.com/docs/chat/channels) that the Member has read.
	 *
	 * @param int $lastConsumedMessageIndex The index of the last [Message](https://www.twilio.com/docs/chat/rest/message-resource) in the [Channel](https://www.twilio.com/docs/chat/channels) that the Member has read.
	 * @return $this Fluent Builder
	 */
	public function setLastConsumedMessageIndex(int $lastConsumedMessageIndex) : self
	{
		$this->options['lastConsumedMessageIndex'] = $lastConsumedMessageIndex;

		return $this;
	}

	/**
	 * The [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) timestamp of the last [Message](https://www.twilio.com/docs/chat/rest/message-resource) read event for the Member within the [Channel](https://www.twilio.com/docs/chat/channels).
	 *
	 * @param \DateTime $lastConsumptionTimestamp The [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) timestamp of the last [Message](https://www.twilio.com/docs/chat/rest/message-resource) read event for the Member within the [Channel](https://www.twilio.com/docs/chat/channels).
	 * @return $this Fluent Builder
	 */
	public function setLastConsumptionTimestamp(\DateTime $lastConsumptionTimestamp) : self
	{
		$this->options['lastConsumptionTimestamp'] = $lastConsumptionTimestamp;

		return $this;
	}

	/**
	 * @return $this Fluent Builder
	 */
	public function setNotificationLevel(string $notificationLevel) : self
	{
		$this->options['notificationLevel'] = $notificationLevel;

		return $this;
	}
}
