<?php

/**
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Intelligence
 * This is the public Twilio REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Twilio\Rest\Intelligence\V2;

use Twilio\Exceptions\TwilioException;
use Twilio\InstanceContext;
use Twilio\Options;
use Twilio\Serialize;
use Twilio\Values;
use Twilio\Version;

class ServiceContext extends InstanceContext
	{
	/**
	 * Initialize the ServiceContext
	 *
	 * @param Version $version Version that contains the resource
	 * @param string $sid A 34 character string that uniquely identifies this Service.
	 */
	public function __construct(
		Version $version,
		$sid
	) {
		parent::__construct($version);

		// Path Solution
		$this->solution = [
			'sid' => $sid,
		];

		$this->uri = '/Services/' . \rawurlencode($sid)
		. '';
	}

	/**
	 * Provide a friendly representation
	 *
	 * @return string Machine friendly representation
	 */
	public function __toString() : string
	{
		$context = [];

		foreach ($this->solution as $key => $value) {
			$context[] = "{$key}={$value}";
		}

		return '[Twilio.Intelligence.V2.ServiceContext ' . \implode(' ', $context) . ']';
	}

	/**
	 * Delete the ServiceInstance
	 *
	 * @throws TwilioException When an HTTP error occurs.
	 * @return bool True if delete succeeds, false otherwise
	 */
	public function delete() : bool
	{

		$headers = Values::of(['Content-Type' => 'application/x-www-form-urlencoded']);

		return $this->version->delete('DELETE', $this->uri, [], [], $headers);
	}

	/**
	 * Fetch the ServiceInstance
	 *
	 * @throws TwilioException When an HTTP error occurs.
	 * @return ServiceInstance Fetched ServiceInstance
	 */
	public function fetch() : ServiceInstance
	{

		$headers = Values::of(['Content-Type' => 'application/x-www-form-urlencoded']);
		$payload = $this->version->fetch('GET', $this->uri, [], [], $headers);

		return new ServiceInstance(
			$this->version,
			$payload,
			$this->solution['sid']
		);
	}

	/**
	 * Update the ServiceInstance
	 *
	 * @param array|Options $options Optional Arguments
	 * @throws TwilioException When an HTTP error occurs.
	 * @return ServiceInstance Updated ServiceInstance
	 */
	public function update(array $options = []) : ServiceInstance
	{

		$options = new Values($options);

		$data = Values::of([
			'AutoTranscribe' => Serialize::booleanToString($options['autoTranscribe']),
			'DataLogging' => Serialize::booleanToString($options['dataLogging']),
			'FriendlyName' => $options['friendlyName'],
			'UniqueName' => $options['uniqueName'],
			'AutoRedaction' => Serialize::booleanToString($options['autoRedaction']),
			'MediaRedaction' => Serialize::booleanToString($options['mediaRedaction']),
			'WebhookUrl' => $options['webhookUrl'],
			'WebhookHttpMethod' => $options['webhookHttpMethod'],
		]);

		$headers = Values::of(['Content-Type' => 'application/x-www-form-urlencoded', 'If-Match' => $options['ifMatch']]);
		$payload = $this->version->update('POST', $this->uri, [], $data, $headers);

		return new ServiceInstance(
			$this->version,
			$payload,
			$this->solution['sid']
		);
	}
}
