<?php

/**
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Verify
 * This is the public Twilio REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Twilio\Rest\Verify\V2\Service\Entity;

use Twilio\Exceptions\TwilioException;
use Twilio\InstanceContext;
use Twilio\ListResource;
use Twilio\Options;
use Twilio\Rest\Verify\V2\Service\Entity\Challenge\NotificationList;
use Twilio\Serialize;
use Twilio\Values;
use Twilio\Version;

/**
 * @property NotificationList $notifications
 */
class ChallengeContext extends InstanceContext
	{
	protected $_notifications;

	/**
	 * Initialize the ChallengeContext
	 *
	 * @param Version $version Version that contains the resource
	 * @param string $serviceSid The unique SID identifier of the Service.
	 * @param string $identity Customer unique identity for the Entity owner of the Challenge. This identifier should be immutable, not PII, length between 8 and 64 characters, and generated by your external system, such as your user's UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
	 * @param string $sid A 34 character string that uniquely identifies this Challenge.
	 */
	public function __construct(
		Version $version,
		$serviceSid,
		$identity,
		$sid
	) {
		parent::__construct($version);

		// Path Solution
		$this->solution = [
			'serviceSid' => $serviceSid,
			'identity' => $identity,
			'sid' => $sid,
		];

		$this->uri = '/Services/' . \rawurlencode($serviceSid)
		. '/Entities/' . \rawurlencode($identity)
		. '/Challenges/' . \rawurlencode($sid)
		. '';
	}

	/**
	 * Magic caller to get resource contexts
	 *
	 * @param string $name Resource to return
	 * @param array $arguments Context parameters
	 * @throws TwilioException For unknown resource
	 * @return InstanceContext The requested resource context
	 */
	public function __call(string $name, array $arguments) : InstanceContext
	{
		$property = $this->{$name};

		if (\method_exists($property, 'getContext')) {
			return \call_user_func_array([$property, 'getContext'], $arguments);
		}

		throw new TwilioException('Resource does not have a context');
	}

	/**
	 * Magic getter to lazy load subresources
	 *
	 * @param string $name Subresource to return
	 * @throws TwilioException For unknown subresources
	 * @return ListResource The requested subresource
	 */
	public function __get(string $name) : ListResource
	{
		if (\property_exists($this, '_' . $name)) {
			$method = 'get' . \ucfirst($name);

			return $this->{$method}();
		}

		throw new TwilioException('Unknown subresource ' . $name);
	}

	/**
	 * Provide a friendly representation
	 *
	 * @return string Machine friendly representation
	 */
	public function __toString() : string
	{
		$context = [];

		foreach ($this->solution as $key => $value) {
			$context[] = "{$key}={$value}";
		}

		return '[Twilio.Verify.V2.ChallengeContext ' . \implode(' ', $context) . ']';
	}

	/**
	 * Fetch the ChallengeInstance
	 *
	 * @throws TwilioException When an HTTP error occurs.
	 * @return ChallengeInstance Fetched ChallengeInstance
	 */
	public function fetch() : ChallengeInstance
	{

		$headers = Values::of(['Content-Type' => 'application/x-www-form-urlencoded']);
		$payload = $this->version->fetch('GET', $this->uri, [], [], $headers);

		return new ChallengeInstance(
			$this->version,
			$payload,
			$this->solution['serviceSid'],
			$this->solution['identity'],
			$this->solution['sid']
		);
	}

	/**
	 * Update the ChallengeInstance
	 *
	 * @param array|Options $options Optional Arguments
	 * @throws TwilioException When an HTTP error occurs.
	 * @return ChallengeInstance Updated ChallengeInstance
	 */
	public function update(array $options = []) : ChallengeInstance
	{

		$options = new Values($options);

		$data = Values::of([
			'AuthPayload' => $options['authPayload'],
			'Metadata' => Serialize::jsonObject($options['metadata']),
		]);

		$headers = Values::of(['Content-Type' => 'application/x-www-form-urlencoded']);
		$payload = $this->version->update('POST', $this->uri, [], $data, $headers);

		return new ChallengeInstance(
			$this->version,
			$payload,
			$this->solution['serviceSid'],
			$this->solution['identity'],
			$this->solution['sid']
		);
	}

	/**
	 * Access the notifications
	 */
	protected function getNotifications() : NotificationList
	{
		if (! $this->_notifications) {
			$this->_notifications = new NotificationList(
				$this->version,
				$this->solution['serviceSid'],
				$this->solution['identity'],
				$this->solution['sid']
			);
		}

		return $this->_notifications;
	}
}
