<?php

/**
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Ip_messaging
 * This is the public Twilio REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Twilio\Rest\IpMessaging\V2\Service\Channel;

use Twilio\Deserialize;
use Twilio\Exceptions\TwilioException;
use Twilio\InstanceResource;
use Twilio\Options;
use Twilio\Values;
use Twilio\Version;

/**
 * @property string|null $sid
 * @property string|null $accountSid
 * @property string|null $serviceSid
 * @property string|null $channelSid
 * @property string|null $type
 * @property string|null $url
 * @property array|null $configuration
 * @property \DateTime|null $dateCreated
 * @property \DateTime|null $dateUpdated
 */
class WebhookInstance extends InstanceResource
{
	/**
	 * Initialize the WebhookInstance
	 *
	 * @param Version $version Version that contains the resource
	 * @param mixed[] $payload The response payload
	 */
	public function __construct(Version $version, array $payload, string $serviceSid, string $channelSid, ?string $sid = null)
	{
		parent::__construct($version);

		// Marshaled Properties
		$this->properties = [
			'sid' => Values::array_get($payload, 'sid'),
			'accountSid' => Values::array_get($payload, 'account_sid'),
			'serviceSid' => Values::array_get($payload, 'service_sid'),
			'channelSid' => Values::array_get($payload, 'channel_sid'),
			'type' => Values::array_get($payload, 'type'),
			'url' => Values::array_get($payload, 'url'),
			'configuration' => Values::array_get($payload, 'configuration'),
			'dateCreated' => Deserialize::dateTime(Values::array_get($payload, 'date_created')),
			'dateUpdated' => Deserialize::dateTime(Values::array_get($payload, 'date_updated')),
		];

		$this->solution = ['serviceSid' => $serviceSid, 'channelSid' => $channelSid, 'sid' => $sid ?: $this->properties['sid'], ];
	}

	/**
	 * Magic getter to access properties
	 *
	 * @param string $name Property to access
	 * @throws TwilioException For unknown properties
	 * @return mixed The requested property
	 */
	public function __get(string $name)
	{
		if (\array_key_exists($name, $this->properties)) {
			return $this->properties[$name];
		}

		if (\property_exists($this, '_' . $name)) {
			$method = 'get' . \ucfirst($name);

			return $this->{$method}();
		}

		throw new TwilioException('Unknown property: ' . $name);
	}

	/**
	 * Provide a friendly representation
	 *
	 * @return string Machine friendly representation
	 */
	public function __toString() : string
	{
		$context = [];

		foreach ($this->solution as $key => $value) {
			$context[] = "{$key}={$value}";
		}

		return '[Twilio.IpMessaging.V2.WebhookInstance ' . \implode(' ', $context) . ']';
	}

	/**
	 * Delete the WebhookInstance
	 *
	 * @throws TwilioException When an HTTP error occurs.
	 * @return bool True if delete succeeds, false otherwise
	 */
	public function delete() : bool
	{

		return $this->proxy()->delete();
	}

	/**
	 * Fetch the WebhookInstance
	 *
	 * @throws TwilioException When an HTTP error occurs.
	 * @return WebhookInstance Fetched WebhookInstance
	 */
	public function fetch() : WebhookInstance
	{

		return $this->proxy()->fetch();
	}

	/**
	 * Update the WebhookInstance
	 *
	 * @param array|Options $options Optional Arguments
	 * @throws TwilioException When an HTTP error occurs.
	 * @return WebhookInstance Updated WebhookInstance
	 */
	public function update(array $options = []) : WebhookInstance
	{

		return $this->proxy()->update($options);
	}

	/**
	 * Generate an instance context for the instance, the context is capable of
	 * performing various actions.  All instance actions are proxied to the context
	 *
	 * @return WebhookContext Context for this WebhookInstance
	 */
	protected function proxy() : WebhookContext
	{
		if (! $this->context) {
			$this->context = new WebhookContext(
				$this->version,
				$this->solution['serviceSid'],
				$this->solution['channelSid'],
				$this->solution['sid']
			);
		}

		return $this->context;
	}
}
