<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateCRUD.php table_name
 *
 * @property int $additionalEmailId MySQL type int(11)
 * @property \App\Record\AdditionalEmail $additionalEmail related record
 * @property string $email MySQL type varchar(100)
 * @property int $memberId MySQL type int(11)
 * @property \App\Record\Member $member related record
 * @property int $verified MySQL type int(1)
 */
abstract class AdditionalEmail extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, NULL, DEFAULT, KEY
		'additionalEmailId' => ['int(11)', 'int', 11, false, null, true, ],
		'email' => ['varchar(100)', 'string', 100, false, null, true, ],
		'memberId' => ['int(11)', 'int', 11, false, null, true, ],
		'verified' => ['int(1)', 'int', 1, false, 0, false, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['additionalEmailId' => true, ];

	protected static string $table = 'additionalEmail';
	}
