<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property int $assistantLeaderTypeId MySQL type int
 * @property \App\Record\AssistantLeaderType $assistantLeaderType related record
 * @property string $name MySQL type varchar(100)
 * @property int $volunteerPoints MySQL type int
 */
abstract class AssistantLeaderType extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'assistantLeaderTypeId' => ['int', 'int', 0, false, ],
		'name' => ['varchar(100)', 'string', 100, false, ],
		'volunteerPoints' => ['int', 'int', 0, false, 0, ],
	];

	/** @var array<string> */
	protected static array $primaryKeys = ['assistantLeaderTypeId', ];

	protected static string $table = 'assistantLeaderType';
	}
