<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?int $assistantLeaderTypeId MySQL type int
 * @property \App\Record\AssistantLeaderType $assistantLeaderType related record
 * @property int $memberId MySQL type int
 * @property \App\Record\Member $member related record
 * @property int $rideId MySQL type int
 * @property \App\Record\Ride $ride related record
 */
abstract class AssistantLeader extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = false;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'assistantLeaderTypeId' => ['int', 'int', 0, true, ],
		'memberId' => ['int', 'int', 0, false, ],
		'rideId' => ['int', 'int', 0, false, ],
	];

	/** @var array<string> */
	protected static array $primaryKeys = ['rideId', 'memberId', ];

	protected static string $table = 'assistantLeader';
	}
