<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?string $additional MySQL type text
 * @property int $auditTrailId MySQL type int
 * @property \App\Record\AuditTrail $auditTrail related record
 * @property ?string $input MySQL type text
 * @property int $memberId MySQL type int
 * @property \App\Record\Member $member related record
 * @property ?string $statement MySQL type text
 * @property string $time MySQL type datetime
 */
abstract class AuditTrail extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, \PHPFUI\ORM\FieldDefinition> */
	protected static array $fields = [];

	/** @var array<string> */
	protected static array $primaryKeys = ['auditTrailId', ];

	protected static string $table = 'auditTrail';

	public function initFieldDefinitions() : static
		{
		if (! \count(static::$fields))
			{
			static::$fields = [
				'additional' => new \PHPFUI\ORM\FieldDefinition('text', 'string', 65535, true, ),
				'auditTrailId' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, false, ),
				'input' => new \PHPFUI\ORM\FieldDefinition('text', 'string', 65535, true, ),
				'memberId' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, false, ),
				'statement' => new \PHPFUI\ORM\FieldDefinition('text', 'string', 65535, true, ),
				'time' => new \PHPFUI\ORM\FieldDefinition('datetime', 'string', 20, false, 'CURRENT_TIMESTAMP', ),
			];
			}

		return $this;
		}
	}
