<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateCRUD.php table_name
 *
 * @property ?string $area MySQL type varchar(255)
 * @property int $bikeShopAreaId MySQL type int(11)
 * @property \App\Record\BikeShopArea $bikeShopArea related record
 * @property ?string $state MySQL type char(2)
 */
abstract class BikeShopArea extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, NULL, DEFAULT, KEY
		'area' => ['varchar(255)', 'string', 255, true, null, false, ],
		'bikeShopAreaId' => ['int(11)', 'int', 11, false, null, true, ],
		'state' => ['char(2)', 'string', 2, true, null, false, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['bikeShopAreaId' => true, ];

	protected static string $table = 'bikeShopArea';
	}
