<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateCRUD.php table_name
 *
 * @property int $blogId MySQL type int(11)
 * @property \App\Record\Blog $blog related record
 * @property string $name MySQL type varchar(100)
 */
abstract class Blog extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, NULL, DEFAULT, KEY
		'blogId' => ['int(11)', 'int', 11, false, null, true, ],
		'name' => ['varchar(100)', 'string', 100, false, null, true, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['blogId' => true, ];

	protected static string $table = 'blog';
	}
