<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?string $description MySQL type text
 * @property string $extension MySQL type char(10)
 * @property int $memberId MySQL type int
 * @property \App\Record\Member $member related record
 * @property ?int $rank MySQL type int
 * @property ?string $title MySQL type varchar(50)
 */
abstract class BoardMember extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = false;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'description' => ['text', 'string', 65535, true, ],
		'extension' => ['char(10)', 'string', 10, false, '', ],
		'memberId' => ['int', 'int', 0, false, ],
		'rank' => ['int', 'int', 0, true, ],
		'title' => ['varchar(50)', 'string', 50, true, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['memberId' => true, ];

	protected static string $table = 'boardMember';
	}
