<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?string $description MySQL type text
 * @property string $extension MySQL type char(10)
 * @property int $memberId MySQL type int
 * @property \App\Record\Member $member related record
 * @property ?int $rank MySQL type int
 * @property ?string $title MySQL type varchar(50)
 */
abstract class BoardMember extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = false;

	/** @var array<string, \PHPFUI\ORM\FieldDefinition> */
	protected static array $fields = [];

	/** @var array<string> */
	protected static array $primaryKeys = ['memberId', ];

	protected static string $table = 'boardMember';

	public function initFieldDefinitions() : static
		{
		if (! \count(static::$fields))
			{
			static::$fields = [
				'description' => new \PHPFUI\ORM\FieldDefinition('text', 'string', 65535, true, ),
				'extension' => new \PHPFUI\ORM\FieldDefinition('char(10)', 'string', 10, false, '', ),
				'memberId' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, false, ),
				'rank' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, true, ),
				'title' => new \PHPFUI\ORM\FieldDefinition('varchar(50)', 'string', 50, true, ),
			];
			}

		return $this;
		}
	}
