<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property int $calendarId MySQL type int
 * @property \App\Record\Calendar $calendar related record
 * @property ?string $description MySQL type text
 * @property ?string $distances MySQL type char(20)
 * @property string $eventDate MySQL type date
 * @property ?int $eventDays MySQL type int
 * @property ?int $eventType MySQL type int
 * @property ?string $location MySQL type varchar(100)
 * @property int $pending MySQL type int
 * @property ?int $price MySQL type int
 * @property ?string $privateContact MySQL type char(50)
 * @property ?string $privateEmail MySQL type char(50)
 * @property ?string $publicContact MySQL type char(50)
 * @property ?string $publicEmail MySQL type char(50)
 * @property ?string $startTime MySQL type time
 * @property ?string $state MySQL type char(2)
 * @property ?string $title MySQL type char(100)
 * @property ?string $webSite MySQL type char(100)
 */
abstract class Calendar extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'calendarId' => ['int', 'int', 0, false, ],
		'description' => ['text', 'string', 65535, true, ],
		'distances' => ['char(20)', 'string', 20, true, ],
		'eventDate' => ['date', 'string', 10, false, ],
		'eventDays' => ['int', 'int', 0, true, ],
		'eventType' => ['int', 'int', 0, true, ],
		'location' => ['varchar(100)', 'string', 100, true, ],
		'pending' => ['int', 'int', 0, false, 1, ],
		'price' => ['int', 'int', 0, true, ],
		'privateContact' => ['char(50)', 'string', 50, true, ],
		'privateEmail' => ['char(50)', 'string', 50, true, ],
		'publicContact' => ['char(50)', 'string', 50, true, ],
		'publicEmail' => ['char(50)', 'string', 50, true, ],
		'startTime' => ['time', 'string', 0, true, ],
		'state' => ['char(2)', 'string', 2, true, ],
		'title' => ['char(100)', 'string', 100, true, ],
		'webSite' => ['char(100)', 'string', 100, true, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['calendarId' => true, ];

	protected static string $table = 'calendar';
	}
