<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateCRUD.php table_name
 *
 * @property ?int $RWGPSId MySQL type int(11)
 * @property \App\Record\RWGPS $RWGPS related record
 * @property int $cueSheetId MySQL type int(11)
 * @property \App\Record\CueSheet $cueSheet related record
 * @property string $dateAdded MySQL type date
 * @property ?string $description MySQL type text
 * @property ?string $destination MySQL type varchar(100)
 * @property ?int $elevation MySQL type int(5)
 * @property ?int $memberId MySQL type int(11)
 * @property \App\Record\Member $member related record
 * @property ?float $mileage MySQL type float
 * @property ?string $name MySQL type varchar(100)
 * @property int $pending MySQL type int(1)
 * @property int $pointsAwarded MySQL type int(11)
 * @property ?string $revisionDate MySQL type date
 * @property ?int $startLocationId MySQL type int(11)
 * @property \App\Record\StartLocation $startLocation related record
 * @property ?int $terrain MySQL type int(1)
 */
abstract class CueSheet extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, NULL, DEFAULT, KEY
		'RWGPSId' => ['int(11)', 'int', 11, true, null, false, ],
		'cueSheetId' => ['int(11)', 'int', 11, false, null, true, ],
		'dateAdded' => ['date', 'string', 10, false, null, false, ],
		'description' => ['text', 'string', 65535, true, null, false, ],
		'destination' => ['varchar(100)', 'string', 100, true, null, false, ],
		'elevation' => ['int(5)', 'int', 5, true, null, false, ],
		'memberId' => ['int(11)', 'int', 11, true, null, false, ],
		'mileage' => ['float', 'float', 0, true, 0, false, ],
		'name' => ['varchar(100)', 'string', 100, true, null, false, ],
		'pending' => ['int(1)', 'int', 1, false, 1, false, ],
		'pointsAwarded' => ['int(11)', 'int', 11, false, 0, false, ],
		'revisionDate' => ['date', 'string', 10, true, null, false, ],
		'startLocationId' => ['int(11)', 'int', 11, true, null, false, ],
		'terrain' => ['int(1)', 'int', 1, true, null, false, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['cueSheetId' => true, ];

	protected static string $table = 'cueSheet';
	}
