<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateCRUD.php table_name
 *
 * @property ?string $address MySQL type varchar(100)
 * @property int $customerId MySQL type int(11)
 * @property \App\Record\Customer $customer related record
 * @property ?string $email MySQL type varchar(100)
 * @property ?string $firstName MySQL type varchar(50)
 * @property ?string $lastName MySQL type varchar(50)
 * @property ?string $password MySQL type varchar(50)
 * @property ?string $state MySQL type char(2)
 * @property ?string $town MySQL type varchar(50)
 * @property ?string $zip MySQL type varchar(10)
 */
abstract class Customer extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, NULL, DEFAULT, KEY
		'address' => ['varchar(100)', 'string', 100, true, null, false, ],
		'customerId' => ['int(11)', 'int', 11, false, null, true, ],
		'email' => ['varchar(100)', 'string', 100, true, null, false, ],
		'firstName' => ['varchar(50)', 'string', 50, true, null, false, ],
		'lastName' => ['varchar(50)', 'string', 50, true, null, false, ],
		'password' => ['varchar(50)', 'string', 50, true, null, false, ],
		'state' => ['char(2)', 'string', 2, true, null, false, ],
		'town' => ['varchar(50)', 'string', 50, true, null, false, ],
		'zip' => ['varchar(10)', 'string', 10, true, null, false, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['customerId' => true, ];

	protected static string $table = 'customer';
	}
