<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property string $fileFolder MySQL type varchar(255)
 * @property int $fileFolderId MySQL type int(11)
 * @property ?int $parentId MySQL type int(11)
 * @property \App\Record\Parent $parent related record
 */
abstract class FileFolder extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, KEY, ALLOWS_NULL, DEFAULT
		'fileFolder' => ['varchar(255)', 'string', 255, false, false, '', ],
		'fileFolderId' => ['int(11)', 'int', 11, true, false, ],
		'parentId' => ['int(11)', 'int', 11, false, true, 0, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['fileFolderId' => true, ];

	protected static string $table = 'fileFolder';
	}
