<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?int $emailType MySQL type int
 * @property int $forumId MySQL type int
 * @property \App\Record\Forum $forum related record
 * @property int $memberId MySQL type int
 * @property \App\Record\Member $member related record
 */
abstract class ForumMember extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = false;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'emailType' => ['int', 'int', 0, true, ],
		'forumId' => ['int', 'int', 0, false, 0, ],
		'memberId' => ['int', 'int', 0, false, ],
	];

	/** @var array<string> */
	protected static array $primaryKeys = ['forumId', 'memberId', ];

	protected static string $table = 'forumMember';
	}
