<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?int $attachments MySQL type int(1)
 * @property ?int $closed MySQL type int(1)
 * @property ?string $description MySQL type text
 * @property ?string $email MySQL type varchar(255)
 * @property int $forumId MySQL type int(11)
 * @property \App\Record\Forum $forum related record
 * @property ?string $name MySQL type varchar(255)
 * @property ?string $whiteList MySQL type text
 */
abstract class Forum extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, KEY, ALLOWS_NULL, DEFAULT
		'attachments' => ['int(1)', 'int', 1, false, true, 0, ],
		'closed' => ['int(1)', 'int', 1, false, true, ],
		'description' => ['text', 'string', 65535, false, true, ],
		'email' => ['varchar(255)', 'string', 255, false, true, ],
		'forumId' => ['int(11)', 'int', 11, true, false, ],
		'name' => ['varchar(255)', 'string', 255, false, true, ],
		'whiteList' => ['text', 'string', 65535, false, true, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['forumId' => true, ];

	protected static string $table = 'forum';
	}
