<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?int $emailType MySQL type int(1)
 * @property int $forumId MySQL type int(11)
 * @property \App\Record\Forum $forum related record
 * @property int $memberId MySQL type int(11)
 * @property \App\Record\Member $member related record
 */
abstract class ForumMember extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = false;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'emailType' => ['int(1)', 'int', 1, true, ],
		'forumId' => ['int(11)', 'int', 11, false, 0, ],
		'memberId' => ['int(11)', 'int', 11, false, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['forumId' => true, 'memberId' => true, ];

	protected static string $table = 'forumMember';
	}
