<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?string $answer MySQL type varchar(255)
 * @property int $gaAnswerId MySQL type int
 * @property \App\Record\GaAnswer $gaAnswer related record
 * @property int $gaEventId MySQL type int
 * @property \App\Record\GaEvent $gaEvent related record
 */
abstract class GaAnswer extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'answer' => ['varchar(255)', 'string', 255, true, ],
		'gaAnswerId' => ['int', 'int', 0, false, ],
		'gaEventId' => ['int', 'int', 0, false, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['gaAnswerId' => true, ];

	protected static string $table = 'gaAnswer';
	}
