<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?int $allowShopping MySQL type int
 * @property ?int $dayOfRegistration MySQL type int
 * @property ?string $description MySQL type text
 * @property string $eventDate MySQL type date
 * @property int $gaEventId MySQL type int
 * @property \App\Record\GaEvent $gaEvent related record
 * @property ?int $includeMembership MySQL type int
 * @property string $lastRegistrationDate MySQL type date
 * @property ?string $location MySQL type char(100)
 * @property ?int $maxRegistrants MySQL type int
 * @property ?string $membershipExpires MySQL type date
 * @property ?int $otherEvent MySQL type int
 * @property ?string $registrar MySQL type char(50)
 * @property ?string $registrarEmail MySQL type char(50)
 * @property ?int $showPreregistration MySQL type int
 * @property ?string $signupMessage MySQL type mediumtext
 * @property ?string $title MySQL type char(100)
 * @property ?int $volunteerDiscount MySQL type int
 * @property ?int $volunteerEvent MySQL type int
 */
abstract class GaEvent extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'allowShopping' => ['int', 'int', 0, true, ],
		'dayOfRegistration' => ['int', 'int', 0, true, ],
		'description' => ['text', 'string', 65535, true, ],
		'eventDate' => ['date', 'string', 10, false, ],
		'gaEventId' => ['int', 'int', 0, false, ],
		'includeMembership' => ['int', 'int', 0, true, ],
		'lastRegistrationDate' => ['date', 'string', 10, false, ],
		'location' => ['char(100)', 'string', 100, true, ],
		'maxRegistrants' => ['int', 'int', 0, true, ],
		'membershipExpires' => ['date', 'string', 10, true, ],
		'otherEvent' => ['int', 'int', 0, true, ],
		'registrar' => ['char(50)', 'string', 50, true, ],
		'registrarEmail' => ['char(50)', 'string', 50, true, ],
		'showPreregistration' => ['int', 'int', 0, true, ],
		'signupMessage' => ['mediumtext', 'string', 16777215, true, ],
		'title' => ['char(100)', 'string', 100, true, ],
		'volunteerDiscount' => ['int', 'int', 0, true, ],
		'volunteerEvent' => ['int', 'int', 0, true, ],
	];

	/** @var array<string> */
	protected static array $primaryKeys = ['gaEventId', ];

	protected static string $table = 'gaEvent';
	}
