<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?string $description MySQL type char(250)
 * @property int $gaEventId MySQL type int
 * @property \App\Record\GaEvent $gaEvent related record
 * @property int $gaIncentiveId MySQL type int
 * @property \App\Record\GaIncentive $gaIncentive related record
 */
abstract class GaIncentive extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'description' => ['char(250)', 'string', 250, true, ],
		'gaEventId' => ['int', 'int', 0, false, ],
		'gaIncentiveId' => ['int', 'int', 0, false, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['gaIncentiveId' => true, ];

	protected static string $table = 'gaIncentive';
	}
