<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?int $active MySQL type int
 * @property ?string $csvField MySQL type varchar(20)
 * @property int $gaEventId MySQL type int
 * @property \App\Record\GaEvent $gaEvent related record
 * @property int $gaOptionId MySQL type int
 * @property \App\Record\GaOption $gaOption related record
 * @property int $maximumAllowed MySQL type int
 * @property string $optionName MySQL type varchar(255)
 * @property int $ordering MySQL type int
 * @property ?float $price MySQL type decimal(7,2)
 * @property int $required MySQL type int
 */
abstract class GaOption extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, \PHPFUI\ORM\FieldDefinition> */
	protected static array $fields = [];

	/** @var array<string> */
	protected static array $primaryKeys = ['gaOptionId', ];

	protected static string $table = 'gaOption';

	public function initFieldDefinitions() : static
		{
		if (! \count(static::$fields))
			{
			static::$fields = [
				'active' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, true, 1, ),
				'csvField' => new \PHPFUI\ORM\FieldDefinition('varchar(20)', 'string', 20, true, ),
				'gaEventId' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, false, ),
				'gaOptionId' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, false, ),
				'maximumAllowed' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, false, 0, ),
				'optionName' => new \PHPFUI\ORM\FieldDefinition('varchar(255)', 'string', 255, false, ),
				'ordering' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, false, 0, ),
				'price' => new \PHPFUI\ORM\FieldDefinition('decimal(7,2)', 'float', 7, true, ),
				'required' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, false, 0, ),
			];
			}

		return $this;
		}
	}
