<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property string $date MySQL type date
 * @property int $gaEventId MySQL type int
 * @property \App\Record\GaEvent $gaEvent related record
 * @property int $gaPriceDateId MySQL type int
 * @property \App\Record\GaPriceDate $gaPriceDate related record
 * @property ?float $price MySQL type decimal(5,2)
 */
abstract class GaPriceDate extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, \PHPFUI\ORM\FieldDefinition> */
	protected static array $fields = [];

	/** @var array<string> */
	protected static array $primaryKeys = ['gaPriceDateId', ];

	protected static string $table = 'gaPriceDate';

	public function initFieldDefinitions() : static
		{
		if (! \count(static::$fields))
			{
			static::$fields = [
				'date' => new \PHPFUI\ORM\FieldDefinition('date', 'string', 10, false, ),
				'gaEventId' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, false, ),
				'gaPriceDateId' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, false, ),
				'price' => new \PHPFUI\ORM\FieldDefinition('decimal(5,2)', 'float', 6, true, ),
			];
			}

		return $this;
		}
	}
