<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateCRUD.php table_name
 *
 * @property ?string $address MySQL type varchar(100)
 * @property ?string $comments MySQL type varchar(50)
 * @property ?string $contact MySQL type varchar(50)
 * @property ?string $contactPhone MySQL type char(15)
 * @property ?string $email MySQL type varchar(50)
 * @property ?int $emailAnnouncements MySQL type int(1)
 * @property ?string $firstName MySQL type varchar(50)
 * @property int $gaEventId MySQL type int(11)
 * @property \App\Record\GaEvent $gaEvent related record
 * @property ?int $gaIncentiveId MySQL type int(11)
 * @property \App\Record\GaIncentive $gaIncentive related record
 * @property ?int $gaRideId MySQL type int(11)
 * @property \App\Record\GaRide $gaRide related record
 * @property int $gaRiderId MySQL type int(11)
 * @property \App\Record\GaRider $gaRider related record
 * @property ?string $lastName MySQL type varchar(50)
 * @property int $memberId MySQL type int(11)
 * @property \App\Record\Member $member related record
 * @property int $pending MySQL type int(1)
 * @property ?string $phone MySQL type varchar(20)
 * @property ?float $pricePaid MySQL type decimal(5,2)
 * @property ?int $prize MySQL type int(6)
 * @property ?int $referral MySQL type int(1)
 * @property string $signedUpOn MySQL type timestamp
 * @property ?string $state MySQL type char(2)
 * @property ?string $town MySQL type varchar(50)
 * @property ?string $zip MySQL type varchar(10)
 */
abstract class GaRider extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, NULL, DEFAULT, KEY
		'address' => ['varchar(100)', 'string', 100, true, null, false, ],
		'comments' => ['varchar(50)', 'string', 50, true, null, false, ],
		'contact' => ['varchar(50)', 'string', 50, true, null, false, ],
		'contactPhone' => ['char(15)', 'string', 15, true, null, false, ],
		'email' => ['varchar(50)', 'string', 50, true, null, false, ],
		'emailAnnouncements' => ['int(1)', 'int', 1, true, 1, false, ],
		'firstName' => ['varchar(50)', 'string', 50, true, null, false, ],
		'gaEventId' => ['int(11)', 'int', 11, false, null, true, ],
		'gaIncentiveId' => ['int(11)', 'int', 11, true, null, false, ],
		'gaRideId' => ['int(11)', 'int', 11, true, null, false, ],
		'gaRiderId' => ['int(11)', 'int', 11, false, null, true, ],
		'lastName' => ['varchar(50)', 'string', 50, true, null, false, ],
		'memberId' => ['int(11)', 'int', 11, false, null, false, ],
		'pending' => ['int(1)', 'int', 1, false, 1, false, ],
		'phone' => ['varchar(20)', 'string', 20, true, '', false, ],
		'pricePaid' => ['decimal(5,2)', 'float', 5, true, null, false, ],
		'prize' => ['int(6)', 'int', 6, true, null, false, ],
		'referral' => ['int(1)', 'int', 1, true, 0, false, ],
		'signedUpOn' => ['timestamp', 'string', 20, true, '', false, ],
		'state' => ['char(2)', 'string', 2, true, null, false, ],
		'town' => ['varchar(50)', 'string', 50, true, null, false, ],
		'zip' => ['varchar(10)', 'string', 10, true, null, false, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['gaRiderId' => true, ];

	protected static string $table = 'gaRider';
	}
