<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?string $description MySQL type varchar(100)
 * @property int $incentiveId MySQL type int(11)
 * @property \App\Record\Incentive $incentive related record
 * @property ?int $notRide MySQL type int(1)
 * @property ?int $points MySQL type int(2)
 */
abstract class Incentive extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, KEY, ALLOWS_NULL, DEFAULT
		'description' => ['varchar(100)', 'string', 100, false, true, ],
		'incentiveId' => ['int(11)', 'int', 11, true, false, ],
		'notRide' => ['int(1)', 'int', 1, false, true, ],
		'points' => ['int(2)', 'int', 2, false, true, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['incentiveId' => true, ];

	protected static string $table = 'incentive';
	}
