<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateCRUD.php table_name
 *
 * @property ?string $description MySQL type text
 * @property ?string $detailLine MySQL type char(100)
 * @property ?int $invoiceId MySQL type int(6)
 * @property \App\Record\Invoice $invoice related record
 * @property ?float $price MySQL type decimal(5,2)
 * @property ?int $quantity MySQL type int(3)
 * @property ?float $shipping MySQL type decimal(5,2)
 * @property ?int $storeItemDetailId MySQL type int(6)
 * @property \App\Record\StoreItemDetail $storeItemDetail related record
 * @property ?int $storeItemId MySQL type int(6)
 * @property \App\Record\StoreItem $storeItem related record
 * @property ?float $tax MySQL type decimal(7,2)
 * @property ?string $title MySQL type char(100)
 * @property ?int $type MySQL type int(5)
 */
abstract class InvoiceItem extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = false;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, NULL, DEFAULT, KEY
		'description' => ['text', 'string', 65535, true, null, false, ],
		'detailLine' => ['char(100)', 'string', 100, true, null, false, ],
		'invoiceId' => ['int(6)', 'int', 6, true, null, true, ],
		'price' => ['decimal(5,2)', 'float', 5, true, null, false, ],
		'quantity' => ['int(3)', 'int', 3, true, null, false, ],
		'shipping' => ['decimal(5,2)', 'float', 5, true, null, false, ],
		'storeItemDetailId' => ['int(6)', 'int', 6, true, null, false, ],
		'storeItemId' => ['int(6)', 'int', 6, true, null, false, ],
		'tax' => ['decimal(7,2)', 'float', 7, true, null, false, ],
		'title' => ['char(100)', 'string', 100, true, null, false, ],
		'type' => ['int(5)', 'int', 5, true, null, false, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['invoiceId' => true, 'storeItemId' => true, 'storeItemDetailId' => true, ];

	protected static string $table = 'invoiceItem';
	}
