<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?string $cutoffDate MySQL type date
 * @property string $date MySQL type date
 * @property ?string $email MySQL type text
 * @property int $jobEventId MySQL type int(11)
 * @property \App\Record\JobEvent $jobEvent related record
 * @property ?string $name MySQL type char(100)
 * @property ?int $organizer MySQL type int(11)
 */
abstract class JobEvent extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, KEY, ALLOWS_NULL, DEFAULT
		'cutoffDate' => ['date', 'string', 10, false, true, ],
		'date' => ['date', 'string', 10, false, false, ],
		'email' => ['text', 'string', 65535, false, true, ],
		'jobEventId' => ['int(11)', 'int', 11, true, false, ],
		'name' => ['char(100)', 'string', 100, false, true, ],
		'organizer' => ['int(11)', 'int', 11, false, true, 0, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['jobEventId' => true, ];

	protected static string $table = 'jobEvent';
	}
