<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateCRUD.php table_name
 *
 * @property string $endTime MySQL type time
 * @property ?int $jobId MySQL type int(6)
 * @property \App\Record\Job $job related record
 * @property int $jobShiftId MySQL type int(11)
 * @property \App\Record\JobShift $jobShift related record
 * @property ?int $needed MySQL type int(2)
 * @property string $startTime MySQL type time
 */
abstract class JobShift extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, NULL, DEFAULT, KEY
		'endTime' => ['time', 'string', 0, false, null, false, ],
		'jobId' => ['int(6)', 'int', 6, true, null, false, ],
		'jobShiftId' => ['int(11)', 'int', 11, false, null, true, ],
		'needed' => ['int(2)', 'int', 2, true, null, false, ],
		'startTime' => ['time', 'string', 0, false, null, false, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['jobShiftId' => true, ];

	protected static string $table = 'jobShift';
	}
