<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateCRUD.php table_name
 *
 * @property ?string $body MySQL type mediumtext
 * @property int $journalItemId MySQL type int(11)
 * @property \App\Record\JournalItem $journalItem related record
 * @property ?int $memberId MySQL type int(11)
 * @property \App\Record\Member $member related record
 * @property string $timeSent MySQL type timestamp
 * @property ?string $title MySQL type char(100)
 */
abstract class JournalItem extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, NULL, DEFAULT, KEY
		'body' => ['mediumtext', 'string', 16777215, true, null, false, ],
		'journalItemId' => ['int(11)', 'int', 11, false, null, true, ],
		'memberId' => ['int(11)', 'int', 11, true, null, false, ],
		'timeSent' => ['timestamp', 'string', 20, true, '', false, ],
		'title' => ['char(100)', 'string', 100, true, null, false, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['journalItemId' => true, ];

	protected static string $table = 'journalItem';
	}
