<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateCRUD.php table_name
 *
 * @property ?string $email MySQL type char(100)
 * @property int $mailItemId MySQL type int(11)
 * @property \App\Record\MailItem $mailItem related record
 * @property int $mailPieceId MySQL type int(11)
 * @property \App\Record\MailPiece $mailPiece related record
 * @property ?int $memberId MySQL type int(11)
 * @property \App\Record\Member $member related record
 * @property ?string $name MySQL type varchar(100)
 */
abstract class MailPiece extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, NULL, DEFAULT, KEY
		'email' => ['char(100)', 'string', 100, true, null, false, ],
		'mailItemId' => ['int(11)', 'int', 11, false, null, true, ],
		'mailPieceId' => ['int(11)', 'int', 11, false, null, true, ],
		'memberId' => ['int(11)', 'int', 11, true, null, false, ],
		'name' => ['varchar(100)', 'string', 100, true, '', false, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['mailPieceId' => true, ];

	protected static string $table = 'mailPiece';
	}
