<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?string $fileName MySQL type mediumblob
 * @property int $mailAttachmentId MySQL type int(11)
 * @property \App\Record\MailAttachment $mailAttachment related record
 * @property int $mailItemId MySQL type int(11)
 * @property \App\Record\MailItem $mailItem related record
 * @property ?string $prettyName MySQL type varchar(255)
 */
abstract class MailAttachment extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'fileName' => ['mediumblob', 'string', 0, true, ],
		'mailAttachmentId' => ['int(11)', 'int', 11, false, ],
		'mailItemId' => ['int(11)', 'int', 11, false, ],
		'prettyName' => ['varchar(255)', 'string', 255, true, '', ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['mailAttachmentId' => true, ];

	protected static string $table = 'mailAttachment';
	}
