<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateCRUD.php table_name
 *
 * @property ?string $acceptedWaiver MySQL type timestamp
 * @property int $allowTexting MySQL type int(1)
 * @property string $cellPhone MySQL type varchar(20)
 * @property int $deceased MySQL type int(1)
 * @property int $discountCount MySQL type int(6)
 * @property ?string $email MySQL type varchar(100)
 * @property int $emailAnnouncements MySQL type tinyint(4)
 * @property int $emailNewsletter MySQL type int(1)
 * @property ?string $emergencyContact MySQL type varchar(50)
 * @property ?string $emergencyPhone MySQL type varchar(20)
 * @property string $extension MySQL type varchar(10)
 * @property ?string $firstName MySQL type varchar(50)
 * @property int $geoLocate MySQL type int(1)
 * @property int $journal MySQL type tinyint(4)
 * @property string $lastLogin MySQL type timestamp
 * @property ?string $lastName MySQL type varchar(50)
 * @property int $leaderPoints MySQL type int(11)
 * @property ?string $license MySQL type char(10)
 * @property ?string $loginAttempts MySQL type varchar(255)
 * @property int $memberId MySQL type int(11)
 * @property \App\Record\Member $member related record
 * @property ?int $membershipId MySQL type int(11)
 * @property \App\Record\Membership $membership related record
 * @property int $newRideEmail MySQL type tinyint(4)
 * @property ?string $password MySQL type varchar(255)
 * @property int $pendingLeader MySQL type int(1)
 * @property string $phone MySQL type varchar(20)
 * @property int $profileHeight MySQL type int(10)
 * @property int $profileWidth MySQL type int(10)
 * @property int $profileX MySQL type int(10)
 * @property int $profileY MySQL type int(10)
 * @property ?int $rideComments MySQL type int(1)
 * @property int $rideJournal MySQL type tinyint(4)
 * @property int $showNoPhone MySQL type tinyint(4)
 * @property int $showNoStreet MySQL type tinyint(4)
 * @property int $showNoTown MySQL type tinyint(4)
 * @property int $showNothing MySQL type tinyint(4)
 * @property int $verifiedEmail MySQL type int(1)
 */
abstract class Member extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, NULL, DEFAULT, KEY
		'acceptedWaiver' => ['timestamp', 'string', 20, true, null, false, ],
		'allowTexting' => ['int(1)', 'int', 1, false, 1, false, ],
		'cellPhone' => ['varchar(20)', 'string', 20, false, '', false, ],
		'deceased' => ['int(1)', 'int', 1, false, 0, false, ],
		'discountCount' => ['int(6)', 'int', 6, false, 0, false, ],
		'email' => ['varchar(100)', 'string', 100, true, null, true, ],
		'emailAnnouncements' => ['tinyint(4)', 'int', 4, false, 0, false, ],
		'emailNewsletter' => ['int(1)', 'int', 1, false, 1, false, ],
		'emergencyContact' => ['varchar(50)', 'string', 50, true, null, false, ],
		'emergencyPhone' => ['varchar(20)', 'string', 20, true, '', false, ],
		'extension' => ['varchar(10)', 'string', 10, false, '', false, ],
		'firstName' => ['varchar(50)', 'string', 50, true, null, true, ],
		'geoLocate' => ['int(1)', 'int', 1, false, 1, false, ],
		'journal' => ['tinyint(4)', 'int', 4, false, 0, false, ],
		'lastLogin' => ['timestamp', 'string', 20, true, '', false, ],
		'lastName' => ['varchar(50)', 'string', 50, true, null, true, ],
		'leaderPoints' => ['int(11)', 'int', 11, false, 0, false, ],
		'license' => ['char(10)', 'string', 10, true, null, false, ],
		'loginAttempts' => ['varchar(255)', 'string', 255, true, null, false, ],
		'memberId' => ['int(11)', 'int', 11, false, null, true, ],
		'membershipId' => ['int(11)', 'int', 11, true, null, true, ],
		'newRideEmail' => ['tinyint(4)', 'int', 4, false, 0, false, ],
		'password' => ['varchar(255)', 'string', 255, true, null, false, ],
		'pendingLeader' => ['int(1)', 'int', 1, false, 0, false, ],
		'phone' => ['varchar(20)', 'string', 20, false, '', false, ],
		'profileHeight' => ['int(10)', 'int', 10, false, 0, false, ],
		'profileWidth' => ['int(10)', 'int', 10, false, 0, false, ],
		'profileX' => ['int(10)', 'int', 10, false, 0, false, ],
		'profileY' => ['int(10)', 'int', 10, false, 0, false, ],
		'rideComments' => ['int(1)', 'int', 1, true, 1, false, ],
		'rideJournal' => ['tinyint(4)', 'int', 4, false, 0, false, ],
		'showNoPhone' => ['tinyint(4)', 'int', 4, false, 0, false, ],
		'showNoStreet' => ['tinyint(4)', 'int', 4, false, 0, false, ],
		'showNoTown' => ['tinyint(4)', 'int', 4, false, 0, false, ],
		'showNothing' => ['tinyint(4)', 'int', 4, false, 0, false, ],
		'verifiedEmail' => ['int(1)', 'int', 1, false, 0, false, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['memberId' => true, ];

	protected static string $table = 'member';
	}
