<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property int $categoryId MySQL type int
 * @property \App\Record\Category $category related record
 * @property int $memberId MySQL type int
 * @property \App\Record\Member $member related record
 */
abstract class MemberCategory extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = false;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'categoryId' => ['int', 'int', 0, false, ],
		'memberId' => ['int', 'int', 0, false, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['memberId' => true, 'categoryId' => true, ];

	protected static string $table = 'memberCategory';
	}
