<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?string $body MySQL type mediumtext
 * @property string $dayOffsets MySQL type varchar(255)
 * @property string $field MySQL type varchar(30)
 * @property ?int $memberId MySQL type int
 * @property \App\Record\Member $member related record
 * @property int $memberNoticeId MySQL type int
 * @property \App\Record\MemberNotice $memberNotice related record
 * @property ?int $overridePreferences MySQL type int
 * @property int $summary MySQL type int
 * @property string $title MySQL type varchar(255)
 */
abstract class MemberNotice extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, \PHPFUI\ORM\FieldDefinition> */
	protected static array $fields = [];

	/** @var array<string> */
	protected static array $primaryKeys = ['memberNoticeId', ];

	protected static string $table = 'memberNotice';

	public function initFieldDefinitions() : static
		{
		if (! \count(static::$fields))
			{
			static::$fields = [
				'body' => new \PHPFUI\ORM\FieldDefinition('mediumtext', 'string', 16777215, true, ),
				'dayOffsets' => new \PHPFUI\ORM\FieldDefinition('varchar(255)', 'string', 255, false, ),
				'field' => new \PHPFUI\ORM\FieldDefinition('varchar(30)', 'string', 30, false, ),
				'memberId' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, true, ),
				'memberNoticeId' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, false, ),
				'overridePreferences' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, true, 0, ),
				'summary' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, false, 1, ),
				'title' => new \PHPFUI\ORM\FieldDefinition('varchar(255)', 'string', 255, false, ),
			];
			}

		return $this;
		}
	}
