<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateCRUD.php table_name
 *
 * @property ?string $bio MySQL type mediumtext
 * @property ?string $fileNameExt MySQL type varchar(10)
 * @property int $memberId MySQL type int(11)
 * @property \App\Record\Member $member related record
 * @property int $memberOfMonthId MySQL type int(11)
 * @property \App\Record\MemberOfMonth $memberOfMonth related record
 * @property string $month MySQL type date
 */
abstract class MemberOfMonth extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, NULL, DEFAULT, KEY
		'bio' => ['mediumtext', 'string', 16777215, true, null, false, ],
		'fileNameExt' => ['varchar(10)', 'string', 10, true, null, false, ],
		'memberId' => ['int(11)', 'int', 11, false, null, false, ],
		'memberOfMonthId' => ['int(11)', 'int', 11, false, null, true, ],
		'month' => ['date', 'string', 10, false, null, false, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['memberOfMonthId' => true, ];

	protected static string $table = 'memberOfMonth';
	}
