<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateCRUD.php table_name
 *
 * @property ?string $client MySQL type varchar(255)
 * @property string $expires MySQL type timestamp
 * @property int $oauthTokenId MySQL type int(11)
 * @property \App\Record\OauthToken $oauthToken related record
 * @property ?int $oauthUserId MySQL type int(11)
 * @property \App\Record\OauthUser $oauthUser related record
 * @property ?string $scopes MySQL type text
 * @property ?string $token MySQL type varchar(255)
 */
abstract class OauthToken extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, NULL, DEFAULT, KEY
		'client' => ['varchar(255)', 'string', 255, true, null, false, ],
		'expires' => ['timestamp', 'string', 20, true, '', false, ],
		'oauthTokenId' => ['int(11)', 'int', 11, false, null, true, ],
		'oauthUserId' => ['int(11)', 'int', 11, true, null, false, ],
		'scopes' => ['text', 'string', 65535, true, null, false, ],
		'token' => ['varchar(255)', 'string', 255, true, null, false, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['oauthTokenId' => true, ];

	protected static string $table = 'oauthToken';
	}
