<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property string $lastLogin MySQL type timestamp
 * @property int $memberId MySQL type int(11)
 * @property \App\Record\Member $member related record
 * @property int $oauthUserId MySQL type int(11)
 * @property \App\Record\OauthUser $oauthUser related record
 * @property ?string $password MySQL type varchar(255)
 * @property ?string $permissions MySQL type text
 * @property ?string $userName MySQL type varchar(100)
 */
abstract class OauthUser extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, KEY, ALLOWS_NULL, DEFAULT
		'lastLogin' => ['timestamp', 'string', 20, false, true, 'CURRENT_TIMESTAMP', ],
		'memberId' => ['int(11)', 'int', 11, false, false, ],
		'oauthUserId' => ['int(11)', 'int', 11, true, false, ],
		'password' => ['varchar(255)', 'string', 255, false, true, ],
		'permissions' => ['text', 'string', 65535, false, true, ],
		'userName' => ['varchar(100)', 'string', 100, false, true, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['oauthUserId' => true, ];

	protected static string $table = 'oauthUser';
	}
