<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?int $categoryId MySQL type int(1)
 * @property \App\Record\Category $category related record
 * @property int $maxRiders MySQL type int(11)
 * @property ?string $maxSpeed MySQL type varchar(5)
 * @property ?string $minSpeed MySQL type varchar(5)
 * @property int $ordering MySQL type int(11)
 * @property ?string $pace MySQL type varchar(20)
 * @property int $paceId MySQL type int(11)
 */
abstract class Pace extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'categoryId' => ['int(1)', 'int', 1, true, ],
		'maxRiders' => ['int(11)', 'int', 11, false, 0, ],
		'maxSpeed' => ['varchar(5)', 'string', 5, true, ],
		'minSpeed' => ['varchar(5)', 'string', 5, true, ],
		'ordering' => ['int(11)', 'int', 11, false, 999999, ],
		'pace' => ['varchar(20)', 'string', 20, true, ],
		'paceId' => ['int(11)', 'int', 11, false, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['paceId' => true, ];

	protected static string $table = 'pace';
	}
