<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?int $categoryId MySQL type int
 * @property \App\Record\Category $category related record
 * @property int $maxRiders MySQL type int
 * @property ?string $maxSpeed MySQL type varchar(5)
 * @property ?string $minSpeed MySQL type varchar(5)
 * @property int $ordering MySQL type int
 * @property ?string $pace MySQL type varchar(20)
 * @property int $paceId MySQL type int
 */
abstract class Pace extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, \PHPFUI\ORM\FieldDefinition> */
	protected static array $fields = [];

	/** @var array<string> */
	protected static array $primaryKeys = ['paceId', ];

	protected static string $table = 'pace';

	public function initFieldDefinitions() : static
		{
		if (! \count(static::$fields))
			{
			static::$fields = [
				'categoryId' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, true, ),
				'maxRiders' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, false, 0, ),
				'maxSpeed' => new \PHPFUI\ORM\FieldDefinition('varchar(5)', 'string', 5, true, ),
				'minSpeed' => new \PHPFUI\ORM\FieldDefinition('varchar(5)', 'string', 5, true, ),
				'ordering' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, false, 999999, ),
				'pace' => new \PHPFUI\ORM\FieldDefinition('varchar(20)', 'string', 20, true, ),
				'paceId' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, false, ),
			];
			}

		return $this;
		}
	}
