<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?float $amount MySQL type decimal(7,2)
 * @property string $createdDate MySQL type date
 * @property ?int $createdMemberNumber MySQL type int(11)
 * @property ?int $invoiceId MySQL type int(10)
 * @property \App\Record\Invoice $invoice related record
 * @property int $paypalRefundId MySQL type int(11)
 * @property \App\Record\PaypalRefund $paypalRefund related record
 * @property ?string $paypaltx MySQL type varchar(20)
 * @property ?string $refundOnDate MySQL type date
 * @property ?string $refundedDate MySQL type date
 * @property ?string $response MySQL type text
 */
abstract class PaypalRefund extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, KEY, ALLOWS_NULL, DEFAULT
		'amount' => ['decimal(7,2)', 'float', 7, false, true, ],
		'createdDate' => ['date', 'string', 10, false, false, ],
		'createdMemberNumber' => ['int(11)', 'int', 11, false, true, ],
		'invoiceId' => ['int(10)', 'int', 10, false, true, ],
		'paypalRefundId' => ['int(11)', 'int', 11, true, false, ],
		'paypaltx' => ['varchar(20)', 'string', 20, false, true, ],
		'refundOnDate' => ['date', 'string', 10, false, true, ],
		'refundedDate' => ['date', 'string', 10, false, true, ],
		'response' => ['text', 'string', 65535, false, true, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['paypalRefundId' => true, ];

	protected static string $table = 'paypalRefund';
	}
