<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?int $parentId MySQL type int(11)
 * @property \App\Record\Parent $parent related record
 * @property string $photoFolder MySQL type varchar(255)
 * @property int $photoFolderId MySQL type int(11)
 */
abstract class PhotoFolder extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, KEY, ALLOWS_NULL, DEFAULT
		'parentId' => ['int(11)', 'int', 11, false, true, 0, ],
		'photoFolder' => ['varchar(255)', 'string', 255, false, false, '', ],
		'photoFolderId' => ['int(11)', 'int', 11, true, false, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['photoFolderId' => true, ];

	protected static string $table = 'photoFolder';
	}
