<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property string $extension MySQL type varchar(10)
 * @property ?int $memberId MySQL type int(11)
 * @property \App\Record\Member $member related record
 * @property string $photo MySQL type varchar(255)
 * @property int $photoFolderId MySQL type int(11)
 * @property \App\Record\PhotoFolder $photoFolder related record
 * @property int $photoId MySQL type int(11)
 * @property int $public MySQL type int(11)
 * @property ?string $taken MySQL type datetime
 * @property int $thumbnail MySQL type int(11)
 * @property string $uploaded MySQL type timestamp
 */
abstract class Photo extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, KEY, ALLOWS_NULL, DEFAULT
		'extension' => ['varchar(10)', 'string', 10, false, false, '', ],
		'memberId' => ['int(11)', 'int', 11, false, true, ],
		'photo' => ['varchar(255)', 'string', 255, false, false, '', ],
		'photoFolderId' => ['int(11)', 'int', 11, false, false, ],
		'photoId' => ['int(11)', 'int', 11, true, false, ],
		'public' => ['int(11)', 'int', 11, false, false, 0, ],
		'taken' => ['datetime', 'string', 20, false, true, ],
		'thumbnail' => ['int(11)', 'int', 11, false, false, 0, ],
		'uploaded' => ['timestamp', 'string', 20, false, false, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['photoId' => true, ];

	protected static string $table = 'photo';
	}
