<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateCRUD.php table_name
 *
 * @property int $memberId MySQL type int(11)
 * @property \App\Record\Member $member related record
 * @property string $photoComment MySQL type varchar(255)
 * @property int $photoCommentId MySQL type int(11)
 * @property int $photoId MySQL type int(11)
 * @property \App\Record\Photo $photo related record
 * @property string $timestamp MySQL type timestamp
 */
abstract class PhotoComment extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, NULL, DEFAULT, KEY
		'memberId' => ['int(11)', 'int', 11, false, null, false, ],
		'photoComment' => ['varchar(255)', 'string', 255, false, '', false, ],
		'photoCommentId' => ['int(11)', 'int', 11, false, null, true, ],
		'photoId' => ['int(11)', 'int', 11, false, null, true, ],
		'timestamp' => ['timestamp', 'string', 20, true, '', false, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['photoCommentId' => true, ];

	protected static string $table = 'photoComment';
	}
