<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property int $frontToBack MySQL type int
 * @property int $leftToRight MySQL type int
 * @property ?int $memberId MySQL type int
 * @property \App\Record\Member $member related record
 * @property int $photoId MySQL type int
 * @property \App\Record\Photo $photo related record
 * @property string $photoTag MySQL type varchar(100)
 * @property int $photoTagId MySQL type int
 * @property int $taggerId MySQL type int
 */
abstract class PhotoTag extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, \PHPFUI\ORM\FieldDefinition> */
	protected static array $fields = [];

	/** @var array<string> */
	protected static array $primaryKeys = ['photoTagId', ];

	protected static string $table = 'photoTag';

	public function initFieldDefinitions() : static
		{
		if (! \count(static::$fields))
			{
			static::$fields = [
				'frontToBack' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, false, ),
				'leftToRight' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, false, ),
				'memberId' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, true, ),
				'photoId' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, false, ),
				'photoTag' => new \PHPFUI\ORM\FieldDefinition('varchar(100)', 'string', 100, false, '', ),
				'photoTagId' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, false, ),
				'taggerId' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, false, ),
			];
			}

		return $this;
		}
	}
