<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?int $editorId MySQL type int
 * @property ?int $leaderPoints MySQL type int
 * @property int $memberId MySQL type int
 * @property \App\Record\Member $member related record
 * @property ?int $oldLeaderPoints MySQL type int
 * @property string $time MySQL type timestamp
 */
abstract class PointHistory extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = false;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'editorId' => ['int', 'int', 0, true, ],
		'leaderPoints' => ['int', 'int', 0, true, 0, ],
		'memberId' => ['int', 'int', 0, false, ],
		'oldLeaderPoints' => ['int', 'int', 0, true, 0, ],
		'time' => ['timestamp', 'string', 20, false, null, ],
	];

	/** @var array<string> */
	protected static array $primaryKeys = [];

	protected static string $table = 'pointHistory';
	}
