<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?int $editorId MySQL type int
 * @property int $memberId MySQL type int
 * @property \App\Record\Member $member related record
 * @property ?int $oldLeaderPoints MySQL type int
 * @property string $time MySQL type datetime
 * @property int $volunteerPoints MySQL type int
 */
abstract class PointHistory extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = false;

	/** @var array<string, \PHPFUI\ORM\FieldDefinition> */
	protected static array $fields = [];

	/** @var array<string> */
	protected static array $primaryKeys = [];

	protected static string $table = 'pointHistory';

	public function initFieldDefinitions() : static
		{
		if (! \count(static::$fields))
			{
			static::$fields = [
				'editorId' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, true, ),
				'memberId' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, false, ),
				'oldLeaderPoints' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, true, 0, ),
				'time' => new \PHPFUI\ORM\FieldDefinition('datetime', 'string', 20, false, 'CURRENT_TIMESTAMP', ),
				'volunteerPoints' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, false, 0, ),
			];
			}

		return $this;
		}
	}
