<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?int $banner MySQL type tinyint(1)
 * @property ?int $blog MySQL type tinyint(1)
 * @property ?string $blogAfter MySQL type varchar(100)
 * @property int $footerMenu MySQL type tinyint(4)
 * @property ?int $header MySQL type tinyint(1)
 * @property ?int $hidden MySQL type tinyint(1)
 * @property int $homePageNotification MySQL type tinyint(4)
 * @property ?string $method MySQL type varchar(200)
 * @property ?string $name MySQL type varchar(200)
 * @property int $publicMenu MySQL type tinyint(4)
 * @property int $publicPageId MySQL type int(11)
 * @property \App\Record\PublicPage $publicPage related record
 * @property ?int $sequence MySQL type int(10)
 * @property ?string $url MySQL type varchar(100)
 */
abstract class PublicPage extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, KEY, ALLOWS_NULL, DEFAULT
		'banner' => ['tinyint(1)', 'int', 1, false, true, 0, ],
		'blog' => ['tinyint(1)', 'int', 1, false, true, 0, ],
		'blogAfter' => ['varchar(100)', 'string', 100, false, true, ],
		'footerMenu' => ['tinyint(4)', 'int', 4, false, false, 0, ],
		'header' => ['tinyint(1)', 'int', 1, false, true, 0, ],
		'hidden' => ['tinyint(1)', 'int', 1, false, true, ],
		'homePageNotification' => ['tinyint(4)', 'int', 4, false, false, 0, ],
		'method' => ['varchar(200)', 'string', 200, false, true, ],
		'name' => ['varchar(200)', 'string', 200, false, true, ],
		'publicMenu' => ['tinyint(4)', 'int', 4, false, false, 1, ],
		'publicPageId' => ['int(11)', 'int', 11, true, false, ],
		'sequence' => ['int(10)', 'int', 10, false, true, 0, ],
		'url' => ['varchar(100)', 'string', 100, false, true, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['publicPageId' => true, ];

	protected static string $table = 'publicPage';
	}
