<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?string $address MySQL type varchar(100)
 * @property ?int $eventId MySQL type int
 * @property \App\Record\Event $event related record
 * @property ?int $invoiceId MySQL type int
 * @property \App\Record\Invoice $invoice related record
 * @property int $memberId MySQL type int
 * @property \App\Record\Member $member related record
 * @property ?int $paymentId MySQL type int
 * @property \App\Record\Payment $payment related record
 * @property ?string $phone MySQL type varchar(20)
 * @property float $pricePaid MySQL type decimal(6,2)
 * @property ?string $reservationFirstName MySQL type varchar(50)
 * @property int $reservationId MySQL type int
 * @property \App\Record\Reservation $reservation related record
 * @property ?string $reservationLastName MySQL type varchar(50)
 * @property ?string $reservationemail MySQL type varchar(50)
 * @property string $signedUpAt MySQL type datetime
 * @property ?string $state MySQL type char(2)
 * @property ?string $town MySQL type varchar(50)
 * @property ?string $zip MySQL type varchar(10)
 */
abstract class Reservation extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, \PHPFUI\ORM\FieldDefinition> */
	protected static array $fields = [];

	/** @var array<string> */
	protected static array $primaryKeys = ['reservationId', ];

	protected static string $table = 'reservation';

	public function initFieldDefinitions() : static
		{
		if (! \count(static::$fields))
			{
			static::$fields = [
				'address' => new \PHPFUI\ORM\FieldDefinition('varchar(100)', 'string', 100, true, ),
				'eventId' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, true, ),
				'invoiceId' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, true, 0, ),
				'memberId' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, false, ),
				'paymentId' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, true, ),
				'phone' => new \PHPFUI\ORM\FieldDefinition('varchar(20)', 'string', 20, true, '', ),
				'pricePaid' => new \PHPFUI\ORM\FieldDefinition('decimal(6,2)', 'float', 6, false, 0.00, ),
				'reservationFirstName' => new \PHPFUI\ORM\FieldDefinition('varchar(50)', 'string', 50, true, ),
				'reservationId' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, false, ),
				'reservationLastName' => new \PHPFUI\ORM\FieldDefinition('varchar(50)', 'string', 50, true, ),
				'reservationemail' => new \PHPFUI\ORM\FieldDefinition('varchar(50)', 'string', 50, true, ),
				'signedUpAt' => new \PHPFUI\ORM\FieldDefinition('datetime', 'string', 20, false, 'CURRENT_TIMESTAMP', ),
				'state' => new \PHPFUI\ORM\FieldDefinition('char(2)', 'string', 2, true, ),
				'town' => new \PHPFUI\ORM\FieldDefinition('varchar(50)', 'string', 50, true, ),
				'zip' => new \PHPFUI\ORM\FieldDefinition('varchar(10)', 'string', 10, true, ),
			];
			}

		return $this;
		}
	}
