<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?int $RWGPSId MySQL type int
 * @property \App\Record\RWGPS $RWGPS related record
 * @property ?int $accident MySQL type int
 * @property ?float $averagePace MySQL type float
 * @property int $commentsDisabled MySQL type int
 * @property ?int $cueSheetId MySQL type int
 * @property \App\Record\CueSheet $cueSheet related record
 * @property string $dateAdded MySQL type datetime
 * @property ?string $description MySQL type mediumtext
 * @property ?int $elevation MySQL type int
 * @property int $maxRiders MySQL type int
 * @property int $memberId MySQL type int
 * @property \App\Record\Member $member related record
 * @property ?string $mileage MySQL type varchar(8)
 * @property ?int $numberOfRiders MySQL type int
 * @property int $paceId MySQL type int
 * @property \App\Record\Pace $pace related record
 * @property int $pending MySQL type int
 * @property int $pointsAwarded MySQL type int
 * @property ?string $regrouping MySQL type varchar(50)
 * @property ?string $releasePrinted MySQL type datetime
 * @property ?string $restStop MySQL type varchar(70)
 * @property string $rideDate MySQL type date
 * @property int $rideId MySQL type int
 * @property \App\Record\Ride $ride related record
 * @property int $rideStatus MySQL type int
 * @property ?int $signupNotifications MySQL type tinyint
 * @property ?int $startLocationId MySQL type int
 * @property \App\Record\StartLocation $startLocation related record
 * @property ?string $startTime MySQL type time
 * @property ?float $targetPace MySQL type decimal(3,1)
 * @property ?string $title MySQL type varchar(100)
 * @property ?int $unaffiliated MySQL type int
 */
abstract class Ride extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, \PHPFUI\ORM\FieldDefinition> */
	protected static array $fields = [];

	/** @var array<string> */
	protected static array $primaryKeys = ['rideId', ];

	protected static string $table = 'ride';

	public function initFieldDefinitions() : static
		{
		if (! \count(static::$fields))
			{
			static::$fields = [
				'RWGPSId' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, true, ),
				'accident' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, true, ),
				'averagePace' => new \PHPFUI\ORM\FieldDefinition('float', 'float', 0, true, ),
				'commentsDisabled' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, false, 0, ),
				'cueSheetId' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, true, ),
				'dateAdded' => new \PHPFUI\ORM\FieldDefinition('datetime', 'string', 20, false, 'CURRENT_TIMESTAMP', ),
				'description' => new \PHPFUI\ORM\FieldDefinition('mediumtext', 'string', 16777215, true, ),
				'elevation' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, true, ),
				'maxRiders' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, false, 0, ),
				'memberId' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, false, ),
				'mileage' => new \PHPFUI\ORM\FieldDefinition('varchar(8)', 'string', 8, true, ),
				'numberOfRiders' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, true, ),
				'paceId' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, false, 0, ),
				'pending' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, false, 0, ),
				'pointsAwarded' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, false, 0, ),
				'regrouping' => new \PHPFUI\ORM\FieldDefinition('varchar(50)', 'string', 50, true, '', ),
				'releasePrinted' => new \PHPFUI\ORM\FieldDefinition('datetime', 'string', 20, true, ),
				'restStop' => new \PHPFUI\ORM\FieldDefinition('varchar(70)', 'string', 70, true, ),
				'rideDate' => new \PHPFUI\ORM\FieldDefinition('date', 'string', 10, false, ),
				'rideId' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, false, ),
				'rideStatus' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, false, 0, ),
				'signupNotifications' => new \PHPFUI\ORM\FieldDefinition('tinyint', 'int', 0, true, 1, ),
				'startLocationId' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, true, ),
				'startTime' => new \PHPFUI\ORM\FieldDefinition('time', 'string', 0, true, ),
				'targetPace' => new \PHPFUI\ORM\FieldDefinition('decimal(3,1)', 'float', 3, true, ),
				'title' => new \PHPFUI\ORM\FieldDefinition('varchar(100)', 'string', 100, true, ),
				'unaffiliated' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, true, 0, ),
			];
			}

		return $this;
		}
	}
