<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?int $RWGPSId MySQL type int(11)
 * @property \App\Record\RWGPS $RWGPS related record
 * @property ?int $accident MySQL type int(1)
 * @property ?float $averagePace MySQL type float
 * @property ?int $commentsDisabled MySQL type int(1)
 * @property ?int $cueSheetId MySQL type int(11)
 * @property \App\Record\CueSheet $cueSheet related record
 * @property string $dateAdded MySQL type timestamp
 * @property ?string $description MySQL type text
 * @property ?int $elevation MySQL type int(5)
 * @property int $maxRiders MySQL type int(11)
 * @property int $memberId MySQL type int(11)
 * @property \App\Record\Member $member related record
 * @property ?string $mileage MySQL type varchar(8)
 * @property ?int $numberOfRiders MySQL type int(2)
 * @property int $paceId MySQL type int(11)
 * @property \App\Record\Pace $pace related record
 * @property int $pointsAwarded MySQL type int(11)
 * @property ?string $regrouping MySQL type varchar(50)
 * @property ?string $releasePrinted MySQL type timestamp
 * @property string $rideDate MySQL type date
 * @property int $rideId MySQL type int(11)
 * @property \App\Record\Ride $ride related record
 * @property ?int $rideStatus MySQL type int(1)
 * @property ?int $signupNotifications MySQL type tinyint(4)
 * @property ?int $startLocationId MySQL type int(11)
 * @property \App\Record\StartLocation $startLocation related record
 * @property ?string $startTime MySQL type varchar(8)
 * @property ?float $targetPace MySQL type decimal(3,1)
 * @property ?string $title MySQL type varchar(100)
 * @property ?int $unaffiliated MySQL type int(1)
 */
abstract class Ride extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, NULL, DEFAULT, KEY
		'RWGPSId' => ['int(11)', 'int', 11, true, null, false, ],
		'accident' => ['int(1)', 'int', 1, true, null, false, ],
		'averagePace' => ['float', 'float', 0, true, null, false, ],
		'commentsDisabled' => ['int(1)', 'int', 1, true, 0, false, ],
		'cueSheetId' => ['int(11)', 'int', 11, true, null, false, ],
		'dateAdded' => ['timestamp', 'string', 20, true, 'CURRENT_TIMESTAMP', false, ],
		'description' => ['text', 'string', 65535, true, null, false, ],
		'elevation' => ['int(5)', 'int', 5, true, null, false, ],
		'maxRiders' => ['int(11)', 'int', 11, false, 0, false, ],
		'memberId' => ['int(11)', 'int', 11, false, null, false, ],
		'mileage' => ['varchar(8)', 'string', 8, true, null, false, ],
		'numberOfRiders' => ['int(2)', 'int', 2, true, null, false, ],
		'paceId' => ['int(11)', 'int', 11, false, 0, false, ],
		'pointsAwarded' => ['int(11)', 'int', 11, false, 0, false, ],
		'regrouping' => ['varchar(50)', 'string', 50, true, '', false, ],
		'releasePrinted' => ['timestamp', 'string', 20, true, null, false, ],
		'rideDate' => ['date', 'string', 10, false, null, false, ],
		'rideId' => ['int(11)', 'int', 11, false, null, true, ],
		'rideStatus' => ['int(1)', 'int', 1, true, 0, false, ],
		'signupNotifications' => ['tinyint(4)', 'int', 4, true, 1, false, ],
		'startLocationId' => ['int(11)', 'int', 11, true, null, false, ],
		'startTime' => ['varchar(8)', 'string', 8, true, null, false, ],
		'targetPace' => ['decimal(3,1)', 'float', 3, true, null, false, ],
		'title' => ['varchar(100)', 'string', 100, true, null, false, ],
		'unaffiliated' => ['int(1)', 'int', 1, true, 0, false, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['rideId' => true, ];

	protected static string $table = 'ride';
	}
