<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?int $incentiveId MySQL type int
 * @property \App\Record\Incentive $incentive related record
 * @property int $rideId MySQL type int
 * @property \App\Record\Ride $ride related record
 */
abstract class RideIncentive extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = false;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'incentiveId' => ['int', 'int', 0, true, ],
		'rideId' => ['int', 'int', 0, false, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['rideId' => true, ];

	protected static string $table = 'rideIncentive';
	}
