<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?int $attended MySQL type int
 * @property ?string $comments MySQL type varchar(200)
 * @property ?int $firstRide MySQL type int
 * @property ?int $firstRideInCategory MySQL type int
 * @property int $memberId MySQL type int
 * @property \App\Record\Member $member related record
 * @property ?int $rideComments MySQL type int
 * @property int $rideId MySQL type int
 * @property \App\Record\Ride $ride related record
 * @property string $signedUpTime MySQL type timestamp
 * @property ?int $status MySQL type int
 */
abstract class RideSignup extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = false;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'attended' => ['int', 'int', 0, true, 0, ],
		'comments' => ['varchar(200)', 'string', 200, true, ],
		'firstRide' => ['int', 'int', 0, true, ],
		'firstRideInCategory' => ['int', 'int', 0, true, ],
		'memberId' => ['int', 'int', 0, false, ],
		'rideComments' => ['int', 'int', 0, true, 1, ],
		'rideId' => ['int', 'int', 0, false, ],
		'signedUpTime' => ['timestamp', 'string', 20, false, null, ],
		'status' => ['int', 'int', 0, true, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['rideId' => true, 'memberId' => true, ];

	protected static string $table = 'rideSignup';
	}
