<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?string $comment MySQL type varchar(255)
 * @property ?float $latitude MySQL type decimal(18,15)
 * @property ?float $longitude MySQL type decimal(18,15)
 * @property int $memberId MySQL type int
 * @property \App\Record\Member $member related record
 * @property int $rideCommentId MySQL type int
 * @property \App\Record\RideComment $rideComment related record
 * @property ?int $rideId MySQL type int
 * @property \App\Record\Ride $ride related record
 * @property string $time MySQL type datetime
 */
abstract class RideComment extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'comment' => ['varchar(255)', 'string', 255, true, ],
		'latitude' => ['decimal(18,15)', 'float', 18, true, ],
		'longitude' => ['decimal(18,15)', 'float', 18, true, ],
		'memberId' => ['int', 'int', 0, false, ],
		'rideCommentId' => ['int', 'int', 0, false, ],
		'rideId' => ['int', 'int', 0, true, 0, ],
		'time' => ['datetime', 'string', 20, false, null, ],
	];

	/** @var array<string> */
	protected static array $primaryKeys = ['rideCommentId', ];

	protected static string $table = 'rideComment';
	}
