<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?string $comment MySQL type varchar(255)
 * @property ?float $latitude MySQL type decimal(18,15)
 * @property ?float $longitude MySQL type decimal(18,15)
 * @property int $memberId MySQL type int(11)
 * @property \App\Record\Member $member related record
 * @property int $rideCommentId MySQL type int(11)
 * @property \App\Record\RideComment $rideComment related record
 * @property ?int $rideId MySQL type int(11)
 * @property \App\Record\Ride $ride related record
 * @property string $time MySQL type timestamp
 */
abstract class RideComment extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, KEY, ALLOWS_NULL, DEFAULT
		'comment' => ['varchar(255)', 'string', 255, false, true, ],
		'latitude' => ['decimal(18,15)', 'float', 18, false, true, ],
		'longitude' => ['decimal(18,15)', 'float', 18, false, true, ],
		'memberId' => ['int(11)', 'int', 11, false, false, ],
		'rideCommentId' => ['int(11)', 'int', 11, true, false, ],
		'rideId' => ['int(11)', 'int', 11, false, true, 0, ],
		'time' => ['timestamp', 'string', 20, false, false, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['rideCommentId' => true, ];

	protected static string $table = 'rideComment';
	}
