<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property int $RWGPSId MySQL type int
 * @property \App\Record\RWGPS $RWGPS related record
 * @property ?string $comment MySQL type text
 * @property string $comments MySQL type varchar(255)
 * @property string $lastEdited MySQL type datetime
 * @property int $memberId MySQL type int
 * @property \App\Record\Member $member related record
 */
abstract class RWGPSComment extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = false;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'RWGPSId' => ['int', 'int', 0, false, ],
		'comment' => ['text', 'string', 65535, true, ],
		'comments' => ['varchar(255)', 'string', 255, false, ],
		'lastEdited' => ['datetime', 'string', 20, false, null, ],
		'memberId' => ['int', 'int', 0, false, ],
	];

	/** @var array<string> */
	protected static array $primaryKeys = ['RWGPSId', 'memberId', ];

	protected static string $table = 'RWGPSComment';
	}
