<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property int $RWGPSId MySQL type int(11)
 * @property \App\Record\RWGPS $RWGPS related record
 * @property int $club MySQL type int(1)
 * @property ?string $csv MySQL type text
 * @property string $description MySQL type varchar(255)
 * @property ?int $elevation MySQL type int(10)
 * @property float $feetPerMile MySQL type decimal(5,1)
 * @property ?string $lastUpdated MySQL type date
 * @property ?float $latitude MySQL type decimal(10,6)
 * @property ?float $longitude MySQL type decimal(10,6)
 * @property ?float $mileage MySQL type decimal(4,1)
 * @property ?string $query MySQL type varchar(255)
 * @property ?int $startLocationId MySQL type int(11)
 * @property \App\Record\StartLocation $startLocation related record
 * @property string $state MySQL type char(2)
 * @property ?int $status MySQL type int(11)
 * @property string $title MySQL type varchar(255)
 * @property string $town MySQL type varchar(50)
 * @property string $zip MySQL type varchar(10)
 */
abstract class RWGPS extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = false;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, KEY, ALLOWS_NULL, DEFAULT
		'RWGPSId' => ['int(11)', 'int', 11, false, false, ],
		'club' => ['int(1)', 'int', 1, false, false, 0, ],
		'csv' => ['text', 'string', 65535, false, true, ],
		'description' => ['varchar(255)', 'string', 255, false, false, '', ],
		'elevation' => ['int(10)', 'int', 10, false, true, ],
		'feetPerMile' => ['decimal(5,1)', 'float', 5, false, false, 0, ],
		'lastUpdated' => ['date', 'string', 10, false, true, ],
		'latitude' => ['decimal(10,6)', 'float', 10, false, true, ],
		'longitude' => ['decimal(10,6)', 'float', 10, false, true, ],
		'mileage' => ['decimal(4,1)', 'float', 4, false, true, ],
		'query' => ['varchar(255)', 'string', 255, false, true, ],
		'startLocationId' => ['int(11)', 'int', 11, false, true, ],
		'state' => ['char(2)', 'string', 2, false, false, '', ],
		'status' => ['int(11)', 'int', 11, false, true, ],
		'title' => ['varchar(255)', 'string', 255, false, false, '', ],
		'town' => ['varchar(50)', 'string', 50, false, false, '', ],
		'zip' => ['varchar(10)', 'string', 10, false, false, '', ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['RWGPSId' => true, ];

	protected static string $table = 'RWGPS';
	}
