<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property int $RWGPSId MySQL type int(11)
 * @property \App\Record\RWGPS $RWGPS related record
 * @property string $comments MySQL type varchar(255)
 * @property string $lastEdited MySQL type timestamp
 * @property int $memberId MySQL type int(11)
 * @property \App\Record\Member $member related record
 */
abstract class RWGPSComment extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = false;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'RWGPSId' => ['int(11)', 'int', 11, false, ],
		'comments' => ['varchar(255)', 'string', 255, false, ],
		'lastEdited' => ['timestamp', 'string', 20, false, null, ],
		'memberId' => ['int(11)', 'int', 11, false, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['RWGPSId' => true, 'memberId' => true, ];

	protected static string $table = 'RWGPSComment';
	}
