<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property int $rideId MySQL type int
 * @property \App\Record\Ride $ride related record
 * @property int $signinSheetId MySQL type int
 * @property \App\Record\SigninSheet $signinSheet related record
 */
abstract class SigninSheetRide extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = false;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'rideId' => ['int', 'int', 0, false, ],
		'signinSheetId' => ['int', 'int', 0, false, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['signinSheetId' => true, 'rideId' => true, ];

	protected static string $table = 'signinSheetRide';
	}
