<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property string $dateAdded MySQL type date
 * @property ?string $ext MySQL type char(10)
 * @property int $memberId MySQL type int
 * @property \App\Record\Member $member related record
 * @property ?int $pending MySQL type int
 * @property int $pointsAwarded MySQL type int
 * @property int $signinSheetId MySQL type int
 * @property \App\Record\SigninSheet $signinSheet related record
 */
abstract class SigninSheet extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'dateAdded' => ['date', 'string', 10, false, ],
		'ext' => ['char(10)', 'string', 10, true, '', ],
		'memberId' => ['int', 'int', 0, false, ],
		'pending' => ['int', 'int', 0, true, 1, ],
		'pointsAwarded' => ['int', 'int', 0, false, 0, ],
		'signinSheetId' => ['int', 'int', 0, false, ],
	];

	/** @var array<string> */
	protected static array $primaryKeys = ['signinSheetId', ];

	protected static string $table = 'signinSheet';
	}
