<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?int $active MySQL type tinyint
 * @property ?string $directions MySQL type text
 * @property ?float $latitude MySQL type decimal(10,6)
 * @property ?string $link MySQL type varchar(255)
 * @property ?float $longitude MySQL type decimal(10,6)
 * @property ?string $name MySQL type varchar(100)
 * @property int $startLocationId MySQL type int
 * @property \App\Record\StartLocation $startLocation related record
 */
abstract class StartLocation extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'active' => ['tinyint', 'int', 0, true, 1, ],
		'directions' => ['text', 'string', 65535, true, ],
		'latitude' => ['decimal(10,6)', 'float', 10, true, ],
		'link' => ['varchar(255)', 'string', 255, true, ],
		'longitude' => ['decimal(10,6)', 'float', 10, true, ],
		'name' => ['varchar(100)', 'string', 100, true, ],
		'startLocationId' => ['int', 'int', 0, false, ],
	];

	/** @var array<string> */
	protected static array $primaryKeys = ['startLocationId', ];

	protected static string $table = 'startLocation';
	}
