<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateCRUD.php table_name
 *
 * @property ?string $detailLine MySQL type char(100)
 * @property ?int $quantity MySQL type int(5)
 * @property ?int $storeItemDetailId MySQL type int(6)
 * @property \App\Record\StoreItemDetail $storeItemDetail related record
 * @property ?int $storeItemId MySQL type int(6)
 * @property \App\Record\StoreItem $storeItem related record
 */
abstract class StoreItemDetail extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = false;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, NULL, DEFAULT, KEY
		'detailLine' => ['char(100)', 'string', 100, true, null, false, ],
		'quantity' => ['int(5)', 'int', 5, true, null, false, ],
		'storeItemDetailId' => ['int(6)', 'int', 6, true, null, false, ],
		'storeItemId' => ['int(6)', 'int', 6, true, null, true, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['storeItemId' => true, 'storeItemDetailId' => true, ];

	protected static string $table = 'storeItemDetail';
	}
