<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?string $extension MySQL type varchar(10)
 * @property ?string $filename MySQL type varchar(255)
 * @property int $sequence MySQL type int(11)
 * @property int $storeItemId MySQL type int(11)
 * @property \App\Record\StoreItem $storeItem related record
 * @property int $storePhotoId MySQL type int(11)
 * @property \App\Record\StorePhoto $storePhoto related record
 */
abstract class StorePhoto extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, KEY, ALLOWS_NULL, DEFAULT
		'extension' => ['varchar(10)', 'string', 10, false, true, ],
		'filename' => ['varchar(255)', 'string', 255, false, true, ],
		'sequence' => ['int(11)', 'int', 11, false, false, ],
		'storeItemId' => ['int(11)', 'int', 11, false, false, ],
		'storePhotoId' => ['int(11)', 'int', 11, true, false, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['storePhotoId' => true, ];

	protected static string $table = 'storePhoto';
	}
