<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateCRUD.php table_name
 *
 * @property string $optionName MySQL type char(100)
 * @property string $optionValues MySQL type varchar(255)
 * @property int $storeOptionId MySQL type int(11)
 * @property \App\Record\StoreOption $storeOption related record
 */
abstract class StoreOption extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, NULL, DEFAULT, KEY
		'optionName' => ['char(100)', 'string', 100, false, '', false, ],
		'optionValues' => ['varchar(255)', 'string', 255, false, '', false, ],
		'storeOptionId' => ['int(11)', 'int', 11, false, null, true, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['storeOptionId' => true, ];

	protected static string $table = 'storeOption';
	}
