<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateCRUD.php table_name
 *
 * @property int $active MySQL type int(1)
 * @property ?int $clothing MySQL type int(1)
 * @property ?string $cut MySQL type char(1)
 * @property ?string $description MySQL type text
 * @property ?int $noShipping MySQL type int(1)
 * @property ?int $parent MySQL type int(5)
 * @property ?int $payByPoints MySQL type int(1)
 * @property ?string $pickupZip MySQL type char(5)
 * @property int $pointsOnly MySQL type int(1)
 * @property ?float $price MySQL type decimal(5,2)
 * @property ?float $shipping MySQL type decimal(5,2)
 * @property int $storeItemId MySQL type int(11)
 * @property \App\Record\StoreItem $storeItem related record
 * @property ?int $taxable MySQL type int(1)
 * @property ?string $title MySQL type char(100)
 * @property int $type MySQL type int(11)
 */
abstract class StoreItem extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, NULL, DEFAULT, KEY
		'active' => ['int(1)', 'int', 1, false, 0, false, ],
		'clothing' => ['int(1)', 'int', 1, true, null, false, ],
		'cut' => ['char(1)', 'string', 1, true, null, false, ],
		'description' => ['text', 'string', 65535, true, null, false, ],
		'noShipping' => ['int(1)', 'int', 1, true, null, false, ],
		'parent' => ['int(5)', 'int', 5, true, null, false, ],
		'payByPoints' => ['int(1)', 'int', 1, true, null, false, ],
		'pickupZip' => ['char(5)', 'string', 5, true, null, false, ],
		'pointsOnly' => ['int(1)', 'int', 1, false, 0, false, ],
		'price' => ['decimal(5,2)', 'float', 5, true, null, false, ],
		'shipping' => ['decimal(5,2)', 'float', 5, true, null, false, ],
		'storeItemId' => ['int(11)', 'int', 11, false, null, true, ],
		'taxable' => ['int(1)', 'int', 1, true, null, false, ],
		'title' => ['char(100)', 'string', 100, true, null, false, ],
		'type' => ['int(11)', 'int', 11, false, 0, false, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['storeItemId' => true, ];

	protected static string $table = 'storeItem';
	}
