<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property string $added MySQL type timestamp
 * @property int $invoiceId MySQL type int(11)
 * @property \App\Record\Invoice $invoice related record
 * @property int $memberId MySQL type int(11)
 * @property \App\Record\Member $member related record
 * @property string $optionsSelected MySQL type varchar(255)
 * @property int $quantity MySQL type int(11)
 * @property int $storeItemId MySQL type int(11)
 * @property \App\Record\StoreItem $storeItem related record
 * @property int $storeOrderId MySQL type int(11)
 * @property \App\Record\StoreOrder $storeOrder related record
 * @property ?string $updated MySQL type timestamp
 */
abstract class StoreOrder extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'added' => ['timestamp', 'string', 20, false, null, ],
		'invoiceId' => ['int(11)', 'int', 11, false, ],
		'memberId' => ['int(11)', 'int', 11, false, ],
		'optionsSelected' => ['varchar(255)', 'string', 255, false, ],
		'quantity' => ['int(11)', 'int', 11, false, ],
		'storeItemId' => ['int(11)', 'int', 11, false, ],
		'storeOrderId' => ['int(11)', 'int', 11, false, ],
		'updated' => ['timestamp', 'string', 20, true, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['storeOrderId' => true, ];

	protected static string $table = 'storeOrder';
	}
