<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateCRUD.php table_name
 *
 * @property int $sequence MySQL type int(11)
 * @property int $storeItemId MySQL type int(11)
 * @property \App\Record\StoreItem $storeItem related record
 * @property int $storeOptionId MySQL type int(11)
 * @property \App\Record\StoreOption $storeOption related record
 */
abstract class StoreItemOption extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = false;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, NULL, DEFAULT, KEY
		'sequence' => ['int(11)', 'int', 11, false, null, false, ],
		'storeItemId' => ['int(11)', 'int', 11, false, null, true, ],
		'storeOptionId' => ['int(11)', 'int', 11, false, null, true, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['storeItemId' => true, 'storeOptionId' => true, ];

	protected static string $table = 'storeItemOption';
	}
