<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?string $description MySQL type text
 * @property string $name MySQL type varchar(255)
 * @property int $surveyId MySQL type int
 * @property \App\Record\Survey $survey related record
 * @property ?string $uploaded MySQL type date
 */
abstract class Survey extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, \PHPFUI\ORM\FieldDefinition> */
	protected static array $fields = [];

	/** @var array<string> */
	protected static array $primaryKeys = ['surveyId', ];

	protected static string $table = 'survey';

	public function initFieldDefinitions() : static
		{
		if (! \count(static::$fields))
			{
			static::$fields = [
				'description' => new \PHPFUI\ORM\FieldDefinition('text', 'string', 65535, true, ),
				'name' => new \PHPFUI\ORM\FieldDefinition('varchar(255)', 'string', 255, false, ),
				'surveyId' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, false, ),
				'uploaded' => new \PHPFUI\ORM\FieldDefinition('date', 'string', 10, true, ),
			];
			}

		return $this;
		}
	}
