<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property int $memberId MySQL type int(11)
 * @property \App\Record\Member $member related record
 * @property int $permissionGroup MySQL type int(11)
 * @property int $revoked MySQL type int(11)
 */
abstract class UserPermission extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = false;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, KEY, ALLOWS_NULL, DEFAULT
		'memberId' => ['int(11)', 'int', 11, true, false, ],
		'permissionGroup' => ['int(11)', 'int', 11, true, false, ],
		'revoked' => ['int(11)', 'int', 11, false, false, 0, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['memberId' => true, 'permissionGroup' => true, ];

	protected static string $table = 'userPermission';
	}
