<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?string $description MySQL type mediumtext
 * @property ?int $editor MySQL type int
 * @property ?string $fileName MySQL type varchar(255)
 * @property ?int $hits MySQL type int
 * @property string $lastEdited MySQL type timestamp
 * @property int $public MySQL type int
 * @property string $title MySQL type varchar(255)
 * @property string $videoDate MySQL type date
 * @property int $videoId MySQL type int
 * @property \App\Record\Video $video related record
 * @property int $videoTypeId MySQL type int
 * @property \App\Record\VideoType $videoType related record
 */
abstract class Video extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'description' => ['mediumtext', 'string', 16777215, true, ],
		'editor' => ['int', 'int', 0, true, ],
		'fileName' => ['varchar(255)', 'string', 255, true, ],
		'hits' => ['int', 'int', 0, true, ],
		'lastEdited' => ['timestamp', 'string', 20, false, null, ],
		'public' => ['int', 'int', 0, false, 0, ],
		'title' => ['varchar(255)', 'string', 255, false, ],
		'videoDate' => ['date', 'string', 10, false, ],
		'videoId' => ['int', 'int', 0, false, ],
		'videoTypeId' => ['int', 'int', 0, false, ],
	];

	/** @var array<string> */
	protected static array $primaryKeys = ['videoId', ];

	protected static string $table = 'video';
	}
