<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateCRUD.php table_name
 *
 * @property ?string $description MySQL type mediumtext
 * @property ?int $editor MySQL type int(6)
 * @property ?string $fileName MySQL type varchar(255)
 * @property ?int $hits MySQL type int(6)
 * @property string $lastEdited MySQL type timestamp
 * @property int $public MySQL type int(11)
 * @property string $title MySQL type varchar(255)
 * @property string $videoDate MySQL type date
 * @property int $videoId MySQL type int(11)
 * @property \App\Record\Video $video related record
 * @property int $videoTypeId MySQL type int(11)
 * @property \App\Record\VideoType $videoType related record
 */
abstract class Video extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, NULL, DEFAULT, KEY
		'description' => ['mediumtext', 'string', 16777215, true, null, false, ],
		'editor' => ['int(6)', 'int', 6, true, null, false, ],
		'fileName' => ['varchar(255)', 'string', 255, true, null, false, ],
		'hits' => ['int(6)', 'int', 6, true, null, false, ],
		'lastEdited' => ['timestamp', 'string', 20, true, '', false, ],
		'public' => ['int(11)', 'int', 11, false, 0, false, ],
		'title' => ['varchar(255)', 'string', 255, false, null, false, ],
		'videoDate' => ['date', 'string', 10, false, null, false, ],
		'videoId' => ['int(11)', 'int', 11, false, null, true, ],
		'videoTypeId' => ['int(11)', 'int', 11, false, null, false, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['videoId' => true, ];

	protected static string $table = 'video';
	}
