<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?int $jobEventId MySQL type int(5)
 * @property \App\Record\JobEvent $jobEvent related record
 * @property ?string $question MySQL type text
 * @property int $volunteerPollId MySQL type int(11)
 * @property \App\Record\VolunteerPoll $volunteerPoll related record
 */
abstract class VolunteerPoll extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, KEY, ALLOWS_NULL, DEFAULT
		'jobEventId' => ['int(5)', 'int', 5, false, true, ],
		'question' => ['text', 'string', 65535, false, true, ],
		'volunteerPollId' => ['int(11)', 'int', 11, true, false, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['volunteerPollId' => true, ];

	protected static string $table = 'volunteerPoll';
	}
