<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateCRUD.php table_name
 *
 * @property ?string $email MySQL type text
 * @property ?int $jobId MySQL type int(6)
 * @property \App\Record\Job $job related record
 * @property ?int $jobShiftId MySQL type int(6)
 * @property \App\Record\JobShift $jobShift related record
 * @property int $memberId MySQL type int(11)
 * @property \App\Record\Member $member related record
 * @property string $notes MySQL type varchar(255)
 * @property ?int $shiftLeader MySQL type int(1)
 * @property string $signedUpDate MySQL type timestamp
 * @property int $volunteerJobShiftId MySQL type int(11)
 * @property \App\Record\VolunteerJobShift $volunteerJobShift related record
 * @property int $worked MySQL type tinyint(4)
 */
abstract class VolunteerJobShift extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, NULL, DEFAULT, KEY
		'email' => ['text', 'string', 65535, true, null, false, ],
		'jobId' => ['int(6)', 'int', 6, true, null, false, ],
		'jobShiftId' => ['int(6)', 'int', 6, true, null, false, ],
		'memberId' => ['int(11)', 'int', 11, false, null, false, ],
		'notes' => ['varchar(255)', 'string', 255, false, '', false, ],
		'shiftLeader' => ['int(1)', 'int', 1, true, null, false, ],
		'signedUpDate' => ['timestamp', 'string', 20, true, '', false, ],
		'volunteerJobShiftId' => ['int(11)', 'int', 11, false, null, true, ],
		'worked' => ['tinyint(4)', 'int', 4, false, 0, false, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['volunteerJobShiftId' => true, ];

	protected static string $table = 'volunteerJobShift';
	}
