<?php

namespace App\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?string $answer MySQL type varchar(100)
 * @property int $volunteerPollAnswerId MySQL type int(11)
 * @property \App\Record\VolunteerPollAnswer $volunteerPollAnswer related record
 * @property ?int $volunteerPollId MySQL type int(6)
 * @property \App\Record\VolunteerPoll $volunteerPoll related record
 */
abstract class VolunteerPollAnswer extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, ALLOWS_NULL, DEFAULT
		'answer' => ['varchar(100)', 'string', 100, true, ],
		'volunteerPollAnswerId' => ['int(11)', 'int', 11, false, ],
		'volunteerPollId' => ['int(6)', 'int', 6, true, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['volunteerPollAnswerId' => true, ];

	protected static string $table = 'volunteerPollAnswer';
	}
