<?php

/**
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Api
 * This is the public Twilio REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Twilio\Rest\Api\V2010\Account;

use Twilio\Exceptions\TwilioException;
use Twilio\InstanceContext;
use Twilio\ListResource;
use Twilio\Options;
use Twilio\Rest\Api\V2010\Account\Recording\AddOnResultList;
use Twilio\Rest\Api\V2010\Account\Recording\TranscriptionList;
use Twilio\Serialize;
use Twilio\Values;
use Twilio\Version;

/**
 * @property AddOnResultList $addOnResults
 * @property TranscriptionList $transcriptions
 * @method \Twilio\Rest\Api\V2010\Account\Recording\AddOnResultContext addOnResults(string $sid)
 * @method \Twilio\Rest\Api\V2010\Account\Recording\TranscriptionContext transcriptions(string $sid)
 */
class RecordingContext extends InstanceContext
	{
	protected $_addOnResults;

	protected $_transcriptions;

	/**
	 * Initialize the RecordingContext
	 *
	 * @param Version $version Version that contains the resource
	 * @param string $accountSid The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Recording resources to delete.
	 * @param string $sid The Twilio-provided string that uniquely identifies the Recording resource to delete.
	 */
	public function __construct(
		Version $version,
		$accountSid,
		$sid
	) {
		parent::__construct($version);

		// Path Solution
		$this->solution = [
			'accountSid' => $accountSid,
			'sid' => $sid,
		];

		$this->uri = '/Accounts/' . \rawurlencode($accountSid)
		. '/Recordings/' . \rawurlencode($sid)
		. '.json';
	}

	/**
	 * Magic caller to get resource contexts
	 *
	 * @param string $name Resource to return
	 * @param array $arguments Context parameters
	 * @throws TwilioException For unknown resource
	 * @return InstanceContext The requested resource context
	 */
	public function __call(string $name, array $arguments) : InstanceContext
	{
		$property = $this->{$name};

		if (\method_exists($property, 'getContext')) {
			return \call_user_func_array([$property, 'getContext'], $arguments);
		}

		throw new TwilioException('Resource does not have a context');
	}

	/**
	 * Magic getter to lazy load subresources
	 *
	 * @param string $name Subresource to return
	 * @throws TwilioException For unknown subresources
	 * @return ListResource The requested subresource
	 */
	public function __get(string $name) : ListResource
	{
		if (\property_exists($this, '_' . $name)) {
			$method = 'get' . \ucfirst($name);

			return $this->{$method}();
		}

		throw new TwilioException('Unknown subresource ' . $name);
	}

	/**
	 * Provide a friendly representation
	 *
	 * @return string Machine friendly representation
	 */
	public function __toString() : string
	{
		$context = [];

		foreach ($this->solution as $key => $value) {
			$context[] = "{$key}={$value}";
		}

		return '[Twilio.Api.V2010.RecordingContext ' . \implode(' ', $context) . ']';
	}

	/**
	 * Delete the RecordingInstance
	 *
	 * @throws TwilioException When an HTTP error occurs.
	 * @return bool True if delete succeeds, false otherwise
	 */
	public function delete() : bool
	{

		$headers = Values::of(['Content-Type' => 'application/x-www-form-urlencoded']);

		return $this->version->delete('DELETE', $this->uri, [], [], $headers);
	}

	/**
	 * Fetch the RecordingInstance
	 *
	 * @param array|Options $options Optional Arguments
	 * @throws TwilioException When an HTTP error occurs.
	 * @return RecordingInstance Fetched RecordingInstance
	 */
	public function fetch(array $options = []) : RecordingInstance
	{

		$options = new Values($options);

		$params = Values::of([
			'IncludeSoftDeleted' => Serialize::booleanToString($options['includeSoftDeleted']),
		]);

		$headers = Values::of(['Content-Type' => 'application/x-www-form-urlencoded']);
		$payload = $this->version->fetch('GET', $this->uri, $params, [], $headers);

		return new RecordingInstance(
			$this->version,
			$payload,
			$this->solution['accountSid'],
			$this->solution['sid']
		);
	}

	/**
	 * Access the addOnResults
	 */
	protected function getAddOnResults() : AddOnResultList
	{
		if (! $this->_addOnResults) {
			$this->_addOnResults = new AddOnResultList(
				$this->version,
				$this->solution['accountSid'],
				$this->solution['sid']
			);
		}

		return $this->_addOnResults;
	}

	/**
	 * Access the transcriptions
	 */
	protected function getTranscriptions() : TranscriptionList
	{
		if (! $this->_transcriptions) {
			$this->_transcriptions = new TranscriptionList(
				$this->version,
				$this->solution['accountSid'],
				$this->solution['sid']
			);
		}

		return $this->_transcriptions;
	}
}
